### ISSUE TITLE
Pie chart renders incorrectly if SQL Query has aggregate, group by and order by

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2227] opened 2017-05-19 19:42 UTC
When building out a pie chart based on the following SQL query:

```sql
select
        count(*) as cnt
    ,   city
from
        `/marklogiclocal/patients`
where
        state = "NY"
group by
        city
order by
        count(*) desc
limit
        10
```

the pie chart is displayed incorrectly. It has just a single city with a sum of all the cities as it's value as shown below. It is expected to have the top 10 cities by number of records based off city.

![incorrect pie chart](https://cloud.githubusercontent.com/assets/828514/26264016/6269ac1a-3c98-11e7-8326-05e6cd189813.png)

We can see that the query works and returns data as expected if we put a **Preview Table** card after the query:

![correct preview table](https://cloud.githubusercontent.com/assets/828514/26264056/96b9674e-3c98-11e7-9051-f342e60161ab.png)

Here is the query string parameters that are being passed in to the chart:

```
q=SELECT%20city%20AS%20category%2C%20SUM(cnt)%20AS%20measure%2C%20null%20AS%20donut%2C%20null%20AS%20parallel%20FROM%20%60%2Fmarklogiclocal%2Fpatients%20workspaces%2FUntitled%20Workspace%201.slam%2F.tmp%2Fout741f6a36-03d6-42c0-9ad7-c2d9be12e1dc%60%20GROUP%20BY%20city%20ORDER%20BY%20city%20ASC
```

Looking at the output of this, there are 1000 rows, and they are all the same, showing a `category` of **NEW YORK** and a `measure` of **44** which is the sum of the counts for the 10 rows.

This works in Old Mongo connector, but does not work in MarkLogic or Spark. When the original query is run in Couchbase we get an error stating `Failed to plan query.: unimplemented EquiJoin: Not currently mapped to N1QL's key join` which is a known issue (Quasar issue #2117 https://github.com/quasar-analytics/quasar/issues/2117)

**Comment by zeeiyerWork** [comment] 2017-05-20 18:06
@cryogenian  and @rabbitonweb  - please take a look. Dropping it in Spark, since we encountered the issue, when testing against the Spark connector (although as stated here, it appears to happen with other connectors such as Marklogic). Unclear if this should be a slamdata issue and whether the chart setup/show somehow corrupts the intent and generates incorrect sql or whether the problem is elsewhere. Bottom line is that given "results" as in the above example (10 rows with just counts) - we want to just reflect that in the pie-chart, but we seem to end up with non-intuitive pie-charts instead, that seem far from the desired WYSIWIG experience.

**Comment by cryogenian** [comment] 2017-05-20 19:27
Front-end doesn't know what connector is used -- I think it's connector issue, because it works with old mongo

**Comment by zeeiyerWork** [comment] 2017-05-24 15:52
@alissapajer , @sellout , @drostron , @rabbitonweb -> This issue relates to # 1806 in Slamdata. Front-end folks however seem to think this is a deeper backend issue........ in that it works against old-Mongo but not against any of the new connectors (Spark, Mark-logic, CB etc.) -> we tested it a few times against Spark, which is why the issue is homed as such. 

Although @cryogenian - one thing i don't understand is what is stopping us from saying the preview table is what we want charted....so forget about generating a new query via chart-setup (just take the :results that drive preview and chart it)- so unsure if there is not a front-end usability issue in here as well.

**Comment by natefaubion** [comment] 2017-05-24 16:11
@zeeiyerWork The preview table just runs the query as is. The chart setup generates queries on top of that with aggregations and groupings. Charting pushes all data processing to the backend, it doesn't chart a data source directly.

**Comment by zeeiyerWork** [comment] 2017-05-24 16:16
@natefaubion -> Yes that's what I am questioning. I understand that all chart related processing happens on the backend today. But am wondering if there is a use case, where there should me a mode, when no back-end invocation is needed. i.e. When all the work has already been done by the backend (as in the case being discussed here, where the query already produced results in a "chartable" form - i.e. attribute"/count" or measure/dimension) and I just want to chart the results. 

So why is the implementation forcing me to re-run a query ..... What if this were a super-expensive query - why should I have to run it twice just to move from tabular to graph presentation styles?

**Comment by natefaubion** [comment] 2017-05-24 16:18
@zeeiyerWork The preview table does not consume the entire data set, it will paginate.

**Comment by natefaubion** [comment] 2017-05-24 16:19
Expensive queries should be mitigated by caching.

**Comment by alissapajer** [comment] 2017-05-24 16:46
@dugdun what do the Preview Table results look like for old mongo and spark/marklogic? Are there any differences in the result of the query if you don't try to make a chart and just view the data as a table?

**Comment by alissapajer** [comment] 2017-05-24 16:49
Also, I think what @zeeiyerWork was commenting on was the fact that, if I understand correctly, in order to create a pie chart from a table, an additional grouping must occur. In other words, given the table results that @dugdun posted above, is is not possible to create a chart that has pie slices sized according to the `cnt` field. And so the frontend is necescsarily performing some additional grouping on top of the query results. Is that correct?

**Comment by natefaubion** [comment] 2017-05-25 16:10
@alissapajer Technically, you aren't creating a pie chart from a table. A table just forwards the resource (it "taps" it, and runs a limited query based on the resource). The chart setup then creates the additional groupings and aggregations based on the settings, which the following chart card will run. These are completely different queries, and while they are forked from the same resource, it's not possible for them to share anything unless we were to pull in the entire data set and just do everything in the frontend.

If the table card _followed_ the chart card, then we could cache the resource in the frontend as part of evaluation (this would be a useful, fairly simple addition to the eval machinery), but it's definitely not commutative.

**Comment by alissapajer** [comment] 2017-05-25 16:39
@natefaubion ok cool, so here's a follow-up question. If the user wants to display a pie chart, are the pie chart groupings/aggregations computed by the frontend, using the initial query results that quasar provides? Or is quasar used again when the user wants to display a chart (e.g. the frontend creates some new sql that it sends to the backend for evaluation)? Or is quasar only used for the initial sql query evaluation, and chart evaluation (groupings, etc) happens solely in the frontend?

**Comment by natefaubion** [comment] 2017-05-25 18:43
@alissapajer The frontend issues a query in chart setup to sample the data for structure (to be replaced by SSTs). It generates a query with all the aggregations and groupings, which is then executed when the user consumes it via a "Show Chart" card or a subsequent table card. No grouping or aggregating happens in the frontend anymore. The table card is not required for this workflow. If the goal is to _just_ display a chart, then ideally (with SSTs) only one query will be issued by the frontend, which happens when the chart is displayed. But if you show the table of a data source as well, it must issue that query right then, and this query is different from the query issued for charting.

**Comment by alissapajer** [comment] 2017-05-25 20:04
@natefaubion awesome, thanks! So, is it possible to get a hold of the query that the frontend issues to the backed when it displays the chart? I think that's what's needed to debug this issue, since the chart is what is incorrect.

**Comment by damonLL** [comment] 2017-05-30 23:35
@alissapajer if it helps, I ran this against with SlamData **4.2.1** against MongoDB, Couchbase and MarkLogic.  Here are the queries that execute during a `Show Chart`.  Actually, I believe the Show Chart card simply references the view, which in turn executes the query mapped to it? (I added newline characters for easier reading on github)

**MongoDB**:
```
SELECT city AS category, SUM(cnt) AS measure, null AS donut, null AS parallel
FROM `/mongodb/Untitled Workspace.slam/.tmp/out79d8e4d0-6435-47bb-9d91-3b79ad8655ba`
GROUP BY city ORDER BY city ASC
```

**Couchbase**:
```
SELECT city AS category, SUM(cnt) AS measure, null AS donut, null AS parallel
FROM `/couchbase/patients-bucket/Untitled Workspace.slam/.tmp/outbd19a19c-ff78-4510-9bfd-5a9fda3dda00`
GROUP BY city ORDER BY city ASC
```

**MarkLogic**:
```
SELECT city AS category, SUM(cnt) AS measure, null AS donut, null AS parallel
FROM `/marklogic/Untitled Workspace.slam/.tmp/outbfb3de5f-9e3c-4b43-a2ad-96bd2a31abe5`
GROUP BY city ORDER BY city ASC
```

Looks like the queries are essentially the same.  MongoDB provides correct pie chart, MarkLogic provides incorrect pie chart with a single piece, and Couchbase returns the error `Failed to plan query.: unimplemented EquiJoin: Not currently mapped to N1QL's key join`

**Comment by rabbitonweb** [comment] 2017-10-12 19:33
Old mongo was providing "correct" pie chart but it was incorrect behavior. Data is already grouped by the query and then "pie chart" functionality groups it one more time. So from the perspective of SQL both marklogic and spark give you the correct results (even if this is not what user wanted). Why? Because they ran aggregation (sum) on already aggregated data, so it is sum of all sums really.

How can we get correct pie charts then? When the only way you  can do it is to create query `"select 1 as count, city from patients` and then run "pie chart" on the data that is being returned which will do the `group by` and aggregations for you.

Downsides:
1. this is counter intuitive - i would prefer to give you data in tabular form and ask you to create charts from it, not to do some sort of your own magic. but this is how charts work, thus there is not much we can do about it
2. you can not really limit the results you would like to see (for example show me only cities that have more then 10 patients).

But regardless of that all, this is not really a bug (nor it is a feature) and it never was. This is basically how charts work in frontend. The reason that old mongo gave you the 🤞 "right" results, was the fact that it *wrongly* interpreted the query - results should be as they are for both spark and marklogic.

Because all of the above, I'm closing this issue. If you don't agree @here please feel free to reopen :)

**Comment by rabbitonweb** [comment] 2017-10-13 18:31
Actually - a bug. Reopening.

**Comment by rabbitonweb** [comment] 2017-10-13 19:21
So I still believe that running aggregation twice is not needed (it kills performance) and we should maybe rethink how pie charts are created (for me personally this is super counter intuitive) BUT nevertheless that query SHOULD work.

It used to give us wrong results but with right schema, now what we get is totally crazy :) 

@alissapajer looked at QScript and said the problem is there. This bug actually blocks a lot of demo workspaces (for all connectors) so the sooner it is fix the better.

**Comment by rabbitonweb** [comment] 2017-10-13 19:26
Pie Chart essentially runs this query
```
select city, sum(cnt) as c from (select city, count(*) as cnt from `/local/patients.data` where state = "NY" group by city order by count(*) desc limit 10) as meh group by city
```

and gives us right now this

```
city            | c[0]          |
-----------------|---------------|
  unexpected: NA | BROOKLYN      |
  unexpected: NA | BROWNVILLE    |
  unexpected: NA | MOUNT VERNON  |
  unexpected: NA | ROCHESTER     |
  unexpected: NA | SOUTHAMPTON   |
  unexpected: NA | BRONX         |
  unexpected: NA | SCOTTSVILLE   |
  unexpected: NA | NEW YORK      |
  unexpected: NA | ALBANY        |
  unexpected: NA | BUFFALO       |
```

**Comment by alissapajer** [comment] 2017-10-13 23:18
We should not ignore result order in the above query since we are ordering the final results.

**Comment by alissapajer** [comment] 2017-10-13 23:22
This version of the query works as expected against mongo 3.4, quasar v25.0.12
```sql
select city, cnt as c from (select city, count(*) as cnt from patients where state = "NY" group by city order by count(*) desc limit 10) as meh group by city order by c desc
```
The notable difference is that in the outer select we select `cnt as c` instead of `sum(cnt) as c`.

**Comment by rabbitonweb** [comment] 2017-11-06 15:12
@zeeiyerWork asked me recently about this issue. Just to clarify: this is QScript issue, @alissapajer was assigned to this task, I think she already knows were the problem is (if I correctly recall the conversation we had)

**Comment by alissapajer** [comment] 2017-11-06 16:10
This will be fixed with `QSU`. We will try running this query again once the initial version of `QSU` is implemented.

**Comment by edmundnoble** [comment] 2017-11-24 01:05
It looks like this query works just fine. I ran the original query from @dugdun on `cities`, and it gave:
```
 city           | cnt |
----------------|-----|
 NEW YORK       |  40 |
 BROOKLYN       |  37 |
 BRONX          |  25 |
 ROCHESTER      |  19 |
 BUFFALO        |  18 |
 STATEN ISLAND  |  12 |
 SYRACUSE       |  10 |
 ALBANY         |   7 |
 JAMAICA        |   6 |
 FLUSHING       |   6 |
```
 Which seems to be correct because it has multiple results, and @rabbitonweb's integration test passes. Is this not working?

**Closed** 2017-11-27 18:48 UTC
Labels: epic: Establish QSU, status: In review, topic: QScript, type: Bug, ☠️
