### ISSUE TITLE
QScript for reduction attempts to access nonexistent reducer

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2571] opened 2017-07-31 16:47 UTC
Certain queries involving reductions result in `QScript` that attempts to reference a nonexistent reducer, one such example is the query from `demo/timeSeriesAggregation.test`
```sql
 SELECT SUM(value) AS measure, timestamp(dt) AS dimension, sensor AS series FROM smalltimeseries GROUP BY sensor, dt ORDER BY sensor ASC, dt ASC
```
which is compiled to
```
Map
├─ Sort
│  ├─ Reduce
│  │  ├─ LeftShift
│  │  │  ├─ Read(/smalltimeseries)
│  │  │  ├─ Struct
│  │  │  │  ╰─ ○
│  │  │  ├─ IdStatus
│  │  │  │  ╰─ IdStatus(ExcludeId)
│  │  │  ╰─ Repair
│  │  │     ╰─ RightSide
│  │  ├─ Bucket
│  │  │  ╰─ List
│  │  │     ╰─ ConcatArrays
│  │  │        ├─ MakeArray
│  │  │        │  ╰─ Guard
│  │  │        │     ├─ ○
│  │  │        │     ├─ Type(Obj(Map[], Some(Top)))
│  │  │        │     ├─ ProjectField
│  │  │        │     │  ├─ ○
│  │  │        │     │  ╰─ Constant(Str(sensor))
│  │  │        │     ╰─ Undefined
│  │  │        ╰─ MakeArray
│  │  │           ╰─ Guard
│  │  │              ├─ ○
│  │  │              ├─ Type(Obj(Map[], Some(Top)))
│  │  │              ├─ ProjectField
│  │  │              │  ├─ ○
│  │  │              │  ╰─ Constant(Str(dt))
│  │  │              ╰─ Undefined
│  │  ├─ Reducers
│  │  │  ├─ Sum
│  │  │  │  ╰─ Guard
│  │  │  │     ├─ Guard
│  │  │  │     │  ├─ ○
│  │  │  │     │  ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │     │  ├─ ProjectField
│  │  │  │     │  │  ├─ ○
│  │  │  │     │  │  ╰─ Constant(Str(value))
│  │  │  │     │  ╰─ Undefined
│  │  │  │     ├─ Type(Int, Dec, or Interval)
│  │  │  │     ├─ Guard
│  │  │  │     │  ├─ ○
│  │  │  │     │  ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │     │  ├─ ProjectField
│  │  │  │     │  │  ├─ ○
│  │  │  │     │  │  ╰─ Constant(Str(value))
│  │  │  │     │  ╰─ Undefined
│  │  │  │     ╰─ Undefined
│  │  │  ├─ Arbitrary
│  │  │  │  ╰─ Guard
│  │  │  │     ├─ Guard
│  │  │  │     │  ├─ ○
│  │  │  │     │  ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │     │  ├─ ProjectField
│  │  │  │     │  │  ├─ ○
│  │  │  │     │  │  ╰─ Constant(Str(dt))
│  │  │  │     │  ╰─ Undefined
│  │  │  │     ├─ Type(Str)
│  │  │  │     ├─ Guard
│  │  │  │     │  ├─ ○
│  │  │  │     │  ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │     │  ├─ ProjectField
│  │  │  │     │  │  ├─ ○
│  │  │  │     │  │  ╰─ Constant(Str(dt))
│  │  │  │     │  ╰─ Undefined
│  │  │  │     ╰─ Undefined
│  │  │  ├─ Arbitrary
│  │  │  │  ╰─ Guard
│  │  │  │     ├─ ○
│  │  │  │     ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │     ├─ ProjectField
│  │  │  │     │  ├─ ○
│  │  │  │     │  ╰─ Constant(Str(sensor))
│  │  │  │     ╰─ Undefined
│  │  │  ╰─ Arbitrary
│  │  │     ╰─ Guard
│  │  │        ├─ ○
│  │  │        ├─ Type(Obj(Map[], Some(Top)))
│  │  │        ├─ ProjectField
│  │  │        │  ├─ ○
│  │  │        │  ╰─ Constant(Str(dt))
│  │  │        ╰─ Undefined
│  │  ╰─ Repair
│  │     ╰─ ConcatArrays
│  │        ├─ ConcatArrays
│  │        │  ├─ ConcatArrays
│  │        │  │  ├─ MakeArray
│  │        │  │  │  ╰─ ConcatArrays
│  │        │  │  │     ├─ ConcatArrays
│  │        │  │  │     │  ├─ ConcatArrays
│  │        │  │  │     │  │  ├─ ConcatArrays
│  │        │  │  │     │  │  │  ├─ ConcatArrays
│  │        │  │  │     │  │  │  │  ├─ ConcatArrays
│  │        │  │  │     │  │  │  │  │  ├─ ConcatArrays
│  │        │  │  │     │  │  │  │  │  │  ├─ MakeArray
│  │        │  │  │     │  │  │  │  │  │  │  ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  │  │  │  │  │  ╰─ MakeArray
│  │        │  │  │     │  │  │  │  │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  │  │  │  │  ╰─ MakeArray
│  │        │  │  │     │  │  │  │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  │  │  │  ╰─ MakeArray
│  │        │  │  │     │  │  │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  │  │  ╰─ MakeArray
│  │        │  │  │     │  │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  │  ╰─ MakeArray
│  │        │  │  │     │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     │  ╰─ MakeArray
│  │        │  │  │     │     ╰─ ReduceIndex(-\/(0))
│  │        │  │  │     ╰─ MakeArray
│  │        │  │  │        ╰─ ReduceIndex(-\/(0))
│  │        │  │  ╰─ MakeArray
│  │        │  │     ╰─ ConcatArrays
│  │        │  │        ├─ ConcatArrays
│  │        │  │        │  ├─ ConcatArrays
│  │        │  │        │  │  ├─ MakeArray
│  │        │  │        │  │  │  ╰─ ReduceIndex(-\/(0))
│  │        │  │        │  │  ╰─ MakeArray
│  │        │  │        │  │     ╰─ ReduceIndex(-\/(0))
│  │        │  │        │  ╰─ MakeArray
│  │        │  │        │     ╰─ ReduceIndex(-\/(0))
│  │        │  │        ╰─ MakeArray
│  │        │  │           ╰─ ReduceIndex(-\/(0))
│  │        │  ╰─ MakeArray
│  │        │     ╰─ ConcatArrays
│  │        │        ├─ ConcatArrays
│  │        │        │  ├─ ConcatArrays
│  │        │        │  │  ├─ MakeArray
│  │        │        │  │  │  ╰─ ConcatArrays
│  │        │        │  │  │     ├─ ConcatArrays
│  │        │        │  │  │     │  ├─ ConcatArrays
│  │        │        │  │  │     │  │  ├─ MakeArray
│  │        │        │  │  │     │  │  │  ╰─ ReduceIndex(-\/(0))
│  │        │        │  │  │     │  │  ╰─ MakeArray
│  │        │        │  │  │     │  │     ╰─ ReduceIndex(-\/(0))
│  │        │        │  │  │     │  ╰─ MakeArray
│  │        │        │  │  │     │     ╰─ ReduceIndex(-\/(0))
│  │        │        │  │  │     ╰─ MakeArray
│  │        │        │  │  │        ╰─ ReduceIndex(-\/(0))
│  │        │        │  │  ╰─ MakeArray
│  │        │        │  │     ╰─ ConcatArrays
│  │        │        │  │        ├─ ConcatArrays
│  │        │        │  │        │  ├─ ConcatArrays
│  │        │        │  │        │  │  ├─ MakeArray
│  │        │        │  │        │  │  │  ╰─ ReduceIndex(-\/(0))
│  │        │        │  │        │  │  ╰─ MakeArray
│  │        │        │  │        │  │     ╰─ ReduceIndex(-\/(0))
│  │        │        │  │        │  ╰─ MakeArray
│  │        │        │  │        │     ╰─ ReduceIndex(-\/(0))
│  │        │        │  │        ╰─ MakeArray
│  │        │        │  │           ╰─ ReduceIndex(-\/(0))
│  │        │        │  ╰─ MakeArray
│  │        │        │     ╰─ ConcatMaps
│  │        │        │        ├─ ConcatMaps
│  │        │        │        │  ├─ ConcatMaps
│  │        │        │        │  │  ├─ ConcatMaps
│  │        │        │        │  │  │  ├─ MakeMap
│  │        │        │        │  │  │  │  ├─ Constant(Str(measure))
│  │        │        │        │  │  │  │  ╰─ ReduceIndex(\/-(0))
│  │        │        │        │  │  │  ╰─ MakeMap
│  │        │        │        │  │  │     ├─ Constant(Str(dimension))
│  │        │        │        │  │  │     ╰─ Timestamp
│  │        │        │        │  │  │        ╰─ ReduceIndex(\/-(1))
│  │        │        │        │  │  ╰─ MakeMap
│  │        │        │        │  │     ├─ Constant(Str(series))
│  │        │        │        │  │     ╰─ ReduceIndex(\/-(2))
│  │        │        │        │  ╰─ MakeMap
│  │        │        │        │     ├─ Constant(Str(__sd__1))
│  │        │        │        │     ╰─ ReduceIndex(\/-(2))
│  │        │        │        ╰─ MakeMap
│  │        │        │           ├─ Constant(Str(__sd__0))
│  │        │        │           ╰─ ReduceIndex(\/-(0))
│  │        │        ╰─ MakeArray
│  │        │           ╰─ ReduceIndex(\/-(2))
│  │        ╰─ MakeArray
│  │           ╰─ ReduceIndex(\/-(8))
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ ProjectIndex
│     │        ├─ ProjectIndex
│     │        │  ├─ ○
│     │        │  ╰─ Constant(Int(2))
│     │        ╰─ Constant(Int(3))
│     ╰─ Ascending
│        ╰─ By
│           ╰─ ProjectIndex
│              ├─ ○
│              ╰─ Constant(Int(3))
╰─ DeleteField
   ├─ DeleteField
   │  ├─ ProjectIndex
   │  │  ├─ ProjectIndex
   │  │  │  ├─ ○
   │  │  │  ╰─ Constant(Int(2))
   │  │  ╰─ Constant(Int(2))
   │  ╰─ Constant(Str(__sd__1))
   ╰─ Constant(Str(__sd__0))
```
the `repair` expression of the reduction attempts to access the 9th reducer when only 4 exist.

This is currently causing a regression for `couchbase` and `spark` connectors.

**Comment by alissapajer** [comment] 2017-08-31 20:21
This `QScript` bug is causing regressions in `next-major` for `spark` and `couchbase` connectors so I've prioritized it into the new mongo epic. It's not as high a priority as regressions that affect mongo, but incorrect `QScript` like this is overall a relatively high priority.

**Comment by alissapajer** [comment] 2017-08-31 21:23
This test is probably where the `java.lang.IndexOutOfBoundsException: 8` in the spark integration tests is coming from.

**Comment by alissapajer** [comment] 2017-08-31 22:14
It looks like the logic is just all wrong in `compactReductions`. Fixing this should fix the incorrect index dereference but won't fix the many many `ReduceIndex(-\/(0))` in the giant repair array. I'll open a separate issue for that.

**Comment by alissapajer** [comment] 2017-08-31 22:56
Issue tracking duplicate structures in `QScript`: https://github.com/quasar-analytics/quasar/issues/2706

**Closed** 2017-09-06 20:29 UTC
Labels: epic: Connector: New Mongo - Initial Production Rollout, status: Fixed in New Mongo, status: In review, topic: QScript, type: Bug, type: Regression
