### ISSUE TITLE
Inconsistent data types returned when working with multiple data types

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2200] opened 2017-05-15 22:52 UTC
Quasar 16.1.6
MongoDB 3.4.x

With the following dataset:

```
rs:PRIMARY> db.t2.find({},{_id:0})
{ "f1" : NumberLong(100) }
{ "f1" : 50 }
{ "f1" : true }
{ "f1" : false }
{ "f1" : 100 }
{ "f1" : "Quasar" }
```

Execute the following query and observe the results:

```
💪 $ SELECT MIN(f1) FROM t2
Query time: 0.0s
 value |
-------|
  50.0 |
```
As one might expect, the minimum number is returned.

Now execute the opposite query:

```
💪 $ SELECT MAX(f1) FROM t2
Query time: 0.0s
 value |
-------|
  true |
```

It now appears a Boolean data type is being returned instead of a number data type.

Whatever the appropriate behavior is supposed to be (i.e. returning booleans or numeric values) it should be consistent.

**Comment by rintcius** [comment] 2017-05-30 15:49
Mongo seems to be inconsistent w.r.t. how it compares aggregates (e.g. [max](https://docs.mongodb.com/manual/reference/operator/aggregation/max/) )

> Returns the maximum value. $max compares both value and type, using the [specified BSON comparison order](https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#bson-types-comparison-order) for values of different types.

and non-aggregates (e.g. [$gt](https://docs.mongodb.com/manual/reference/operator/query/gt/)

> $gt selects those documents where the value of the field is greater than (i.e. >) the specified value.
> For most data types, comparison operators only perform comparisons on fields where the BSON type matches the query value’s type. MongoDB supports limited cross-BSON comparison through Type Bracketing.

**Comment by sellout** [comment] 2017-05-30 15:49
So, this is a bug, but it’s not the one described here. We have a total ordering of all `Comparable` values, arranged roughly by the “size” of the type, so (e.g.) `Null < Boolean < Number < String`.

Therefore, `SELECT MIN(f1) FROM t2` should return `false` and `SELECT MAX(f1) FROM t2` should return `"Quasar"`.

The problem is that forcing our ordering on Mongo really pessimises performance. So currently we let MongoDB use [its internal total ordering](https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#bson-types-comparison-order) which matches the behavior you see there.

@jdegoes I’m actually inclined to reduce the strictness of our ordering definition, providing our ordering as a recommendation, but allowing connectors to use a different one for performance reasons (with maybe an extra flag in the request to indicate how heterogeneous types should be handled – e.g., “best effort” vs “strict”).

If a customer wants to only see the min/max number, they should pre-filter using something like
```sql
select min(f1) from t2 where type_of(f1) = "integer" or type_of(f1) = "decimal"
```
(and we should probably add some type-classy operator like `satisfies(f1, "number")` to make it simpler?)

**Comment by jdegoes** [comment] 2017-05-30 18:51
@sellout I think that's OK. For heterogeneous collections of values, we can state recommended but not required ordering. Any other solution will not be performant for some connectors.

**Comment by sellout** [comment] 2017-06-22 15:49
Closing this, as the current behavior is what’s expected.

**Closed by sellout** 2017-06-22 15:49 UTC
Labels: epic: Connector: MongoDB Overhaul, status: In progress, topic: MongoDB

**Comment by zeeiyerWork** [comment] 2017-07-11 00:06
@dugdun -> If you can add some documentation around this. i.e. if you have a t2 with heterogeneous types - (e.g. numbers and strings and you want min of just the numbers) 
--- select min(f1) from t2 where type_of(f1) = "integer" or type_of(f1) = "decimal"

**Comment by sellout** [comment] 2017-07-11 00:43
And there should maybe be a pointer to a doc describing our total ordering of values.
1. Quasar defines a total ordering like: null < boolean < byte < character < number < array < map, and
2. connectors are _encouraged_ to support that ordering, but _may_ use a different one for performance reasons (e.g., Mongo uses https://docs.mongodb.com/manual/reference/bson-type-comparison-order/)
