### ISSUE TITLE
MarkLogic returns no results when using IN statement

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2123] opened 2017-04-29 04:11 UTC
SlamData version 4.1.5
MarkLogic version 8.0

The following query:
```
SELECT *
FROM `/tvshow` AS t
WHERE
   t.friends IN ("Jin")
```
does not work.  Tested against documents like this:
```
{
	"name" : "Sawyer",
	"gender" : "male",
	"occupation" : "Scam Artist",
	"station" : "Swan",
	"friends" : [
		"Kate",
		"Juliet",
		"Jin"
	]
}
```

SlamData returns `Selected resource is empty`. 

Works when tested against MongoDB.

**Comment by wemrysi** [comment] 2017-04-29 15:45
@damonLL @sellout Is that the correct semantics for `IN`? I'd expect something like `select * from /tvshow as t where "Jin" IN t.friends`.

**Comment by sellout** [comment] 2017-04-29 16:39
Neither of those should work.

You want
```sql
select * from `/tvshow` as t where within("Jin", t.friends)
```
I think
```sql
select * from `/tvshow` as t where "Jin" in t.friends[*]
```
may also work. `IN` requires a set, not an array, and `within()` is like `in`, but accepts an array. And yeah, in both cases, the set/array is the second argument.

I imagine it’s “working” on Mongo because we’re not avoiding Mongo’s magic handling of arrays somewhere (i.e., something is true for an array if it’s true for any element of the array).

**Comment by wemrysi** [comment] 2017-05-03 22:09
Closing this as I've confirmed that `within` works on MarkLogic as intended

```sql
 select * from zips where within(36.732335, loc)
```
yields
```
 _id    | city     | loc[0]     | loc[1]     | pop   | state |
--------|----------|------------|------------|-------|-------|
 64843  | GOODMAN  |  -94.39855 |  36.732335 |  2025 | MO    |
```
@sellout do you want me to open an issue for MongoDB to track the unexpected behavior, or does the QScript connector render this moot?

**Closed by wemrysi** 2017-05-03 22:09 UTC
Labels: epic: Connector: Marklogic Overhaul

**Comment by sellout** [comment] 2017-05-03 22:22
@wemrysi Yeah, it looks like this is still a problem in Mongo-QScript, so if you or @damonLL could open an issue for that, that’d be great.

**Comment by damonLL** [comment] 2017-06-01 19:41
@sellout will this be an issue with the new Mongo connector? If not, probably just leave it unaddressed.
