### ISSUE TITLE
MarkLogic returns no results when querying nested data

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1699] opened 2016-11-14 00:03 UTC
This query returns no results, but the documents have been verified to exist.

```
select first_name, last_name from patients where codes[*].code = "S72.065C"
```

The `explain` output for that query in the REPL is attached.

[explain-nested-query.txt](https://github.com/quasar-analytics/quasar/files/588181/explain-nested-query.txt)

**Comment by wemrysi** [comment] 2016-11-18 18:57
Thanks for the report, I've confirmed on current master that this is still an issue, likely due to joins.

**Comment by wemrysi** [comment] 2017-05-04 17:34
This was fixed via #1912 and testing this on quasar `master` shows it is working properly for both `XML` and `JSON` documents in MarkLogic.

**Closed by wemrysi** 2017-05-04 17:34 UTC
Labels: epic: Connector: Marklogic Overhaul, topic: MarkLogic, type: Bug
