### ISSUE TITLE
Take advantage of MongoDB array matching semantics

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1960] opened 2017-03-12 16:21 UTC
Quasar generated physical plans for MongoDB currently `$unwind` to perform any filtering on arrays. However, MongoDB cannot "see through" unwind, which means that array indices cannot be taken advantage of in any so-compiled query.

To fix this problem, we should ensure that an initial `$match` contains as much of the predicate as we can faithfully push to the front of the query. Note that it does not have to be the full predicate, since we can always `$unwind` on the remainder and re-evaluate the predicate condition to achieve the full predicate filter. The only requirement is that the initial `$match` not discard anything which might subsequently be retained by the full predicate filter.

## Data

```javascript
{
    “org_id” : “abc”,
    “cp_org_id” : “xyz”,
    “trade_id” : “1234”,
    “valuation_date” : “2017-02-02”,
    // … other trade fields, just name/value pairs, mostly strings …
    “sensitivities” : [ {
      “amount_double” : 12345.123,
      // … around 5-10 name/value pair fields per sensitivity with an amount_double field that is a double in Mongo 3.2, we will likely use the new number field in our planned Mongo 3.4 warehouse
     }, {
      // … around 20-50 sensitivities per trade
     }]
}
```

## Query

```sql
SELECT
 t.cp_org_id,
SUM(t.sensitivities[*].amount_double) AS amount_total
FROM `/test/trades/trade` AS t
WHERE t.valuation_date = :Date AND t.org_id = :Organization
GROUP BY t.cp_org_id
```

## Quasar Plan

```javascript
db.trade.aggregate(
  [
    { $unwind : "$sensitivities" },
    { $match: { $and: [ { valuation_date: { $gte: new Date(1485907200000) } }, { valuation_date: { $lt: new Date(1485993600000) } }, { org_id: "m10002015316ORG2" } ] } },
    { $group : { _id : "$cp_org_id" , amount_total : { $sum : "$sensitivities.amount_double" } } },
  ]
 )
```

## Hand-Optimized MongoDB Plan

```javascript
db.trade.aggregate(
  [
    { $match: { $and: [ { valuation_date: { $gte: new Date(1485907200000) } }, { valuation_date: { $lt: new Date(1485993600000) } }, { org_id: "m10002015316ORG2" } ] } },
    { $unwind : "$sensitivities" },
    { $group : { _id : "$cp_org_id" , amount_total : { $sum : "$sensitivities.amount_double" } } },
  ]
 )
```

**Comment by sellout** [comment] 2017-06-22 16:29
Duplicate of #1880.

**Closed by sellout** 2017-06-22 16:29 UTC
Labels: epic: Connector: MongoDB Overhaul, topic: MongoDB, type: Enhancement
