### ISSUE TITLE
Move SparkCore to BackendModule

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#2216] opened 2017-05-18 16:16 UTC
- [x] spark-local
- [x] spark-hdfs
~~- [ ] spark-elastic~~ (moved to https://github.com/quasar-analytics/quasar/issues/2715)
~~- [ ]  spark-cassandra~~ (moved to https://github.com/quasar-analytics/quasar/issues/2716)

**Comment by zeeiyerWork** [comment] 2017-05-20 19:33
Closing this because it is a duplicate of #2096

**Closed** 2017-09-03 19:33 UTC
Labels: epic: Backend Abstraction in Connectors, epic: Connector: New Mongo - Initial Production Rollout, status: In progress, topic: Spark, type: Techdebt
