### ISSUE TITLE
dangling reference for query in PlannerSpec

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3174] opened 2017-11-23 18:29 UTC
This query from `PlannerSpec` fails with a dangling reference:

`select distinct loc || [pop - 1] as p1, pop - 1 as p2 from zips group by territory order by p2`

This can either be a consequence of incorrect qscript or something in mongo

**Comment by jsantos17** [comment] 2017-11-23 21:24
`p2` is the dangling reference. This looks remarkably similar to #3154. 

`city` and `__sd__0` [here](https://gist.github.com/djspiewak/5c82fcbba6a902f0a54cff8076fcef49#file-mongo-failure-txt-L989) dangling references as well.

Same [here](https://gist.github.com/djspiewak/9e9448ef9ba972f5ba563741f4e44ce1#file-mongo-failure-txt-L632): `pop` doesn't refer to anything

And [here](https://gist.github.com/djspiewak/cc5cdae45b1917ccb9f2c709ce25fff5#file-mongo-failure-txt-L1739)

**Comment by jsantos17** [comment] 2017-11-27 16:15
I'm reasonably certain this is happening because of #3154. I'm closing this.

**Closed by jsantos17** 2017-11-27 16:15 UTC
Labels: topic: MongoDB, ☠️

**Comment by jsantos17** [comment] 2017-11-29 16:48
I have confirmed this is a manifestation of the problem in #3154. This query is also fixed there.
