### ISSUE TITLE
Couchbase filesystem issues

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1930] opened 2017-02-24 16:11 UTC
Here are a couple GIFs showing some issues I'm having with the Couchbase connector and the frontend.

When I'm browsing in the Open card (which checks metadata to verify), it will always tell me something doesn't exist, which it clearly does, because I just pulled it from the listing. When I reload it doesn't have an issue.

![couchbase-dne](https://cloud.githubusercontent.com/assets/144058/23310708/0dde82d0-fa79-11e6-947b-d27e3ea1fcfc.gif)

When I make changes which result in a view being invalidated (DELETE and then a fresh PUT), I get a strange error:

```
Error compiling query: An unknown error ocurred: 400 "{ \"error\": { \"status\": \"No files to read from.\", \"detail\": { \"message\": \"No paths provided to read from.\", \"dirs\": [] } } }"
```

![couchbase-nofile](https://cloud.githubusercontent.com/assets/144058/23310813/60b80e7c-fa79-11e6-883e-b5b0c4a34cb1.gif)

Again, reloading seems to fix the issue, so maybe something related to latency? Not sure. When I add a "Preview Table" card, the first query often time doesn't go through (yielding a blank screen). But I get an accurate count, so I can page forward and back, which will work.

**Comment by drostron** [comment] 2017-02-24 16:47
@natefaubion I'm not yet able to reproduce what you're seeing. Could you post a screenshot of your indexes listed in the corresponding Couchbase Console tab?

**Comment by natefaubion** [comment] 2017-02-24 16:53
<img width="1062" alt="screen shot 2017-02-24 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/144058/23312458/74bfb46e-fa7f-11e6-8cbd-603267b3b8bc.png">

**Comment by drostron** [comment] 2017-02-24 17:02
@natefaubion Can you add the following index via the Query tab and see if behavior changes for you?

```
CREATE INDEX `idx_beer_sample_type` ON `beer-sample`(`type`)
```

**Comment by natefaubion** [comment] 2017-02-24 17:04
It runs faster, but I still get the same error behavior.

**Comment by jdegoes** [comment] 2017-02-24 17:10
@drostron Also, if indexes are required for correct behavior, perhaps we should create them ourselves?

**Comment by drostron** [comment] 2017-02-24 17:16
@jdegoes That could make sense or at least check for them and issue a warning in their absence. It seems that this issue is stemming from something else though. I noticed that memory optimized indexes aren't enabled in @natefaubion's CB server. I'm going to try that out locally to see if I can replicate.

**Comment by drostron** [comment] 2017-02-24 18:58
I've tried both CB 4.5 and 4.5 without memory optimized indexes and without an index on type and am unable to reproduce. Definitely saw the issue with @natefaubion's setup when pairing and it appears that empty results are being returned from CB intermittently. As far as we could tell our CB Server configs were the same. I'll try a few more variations to see if that helps manifest the behavior.

**Comment by drostron** [comment] 2017-05-10 16:25
Closing due to being unable to reproduce. @natefaubion please reopen if you run into this again.

**Closed by drostron** 2017-05-10 16:25 UTC
Labels: epic: Connector: Couchbase Overhaul, topic: Couchbase, type: Bug
