### ISSUE TITLE
Search card failed XHR response with Marklogic

### ISSUE THREAD

**Issue by Cmdv** [quasar-analytics/quasar#2341] opened 2017-06-16 16:22 UTC
### Description

Search card seems to return 500 on a GET query. You are still able to create additional cards but no data is present.

### Reproduction guide

Mount Marklogic -> create workspace -> add `open card` select `zips` -> add `search card`, type _springfield_

You can continue and add `pivot table`, clicking column you are presented with no options. Such as expected `city` + `pop`. When looking at data through `preview table` the data rows are exactly the same as on mongoDB where this action works.

**Observed behaviour:**
GET request return 500 on `http://localhost:63175/data/fs/testDb/Untitled%20Workspace.slam/.tmp/out758c73ce-b0d3-4627-82ff-f445fdf82caf?offset=0&limit=300`

```
Physical filesystem error.: XDMP-ARGTYPE: (err:XPTY0004) fn:matches(number-node{15338}, "^.*springfield.*$", "i") -- arg1 is not of type xs:string? on line 93 ---BEGIN QUERY--- xquery version "1.0-ml"; declare namespace ejson = "http://quasar-analytics.org/ejson"; declare namespace qscript = "http://quasar-analytics.org/qscript"; declare function ejson:cast-if-node($item as item()?) as item()? { typeswitch($item) case $n as node() return ejson:json-node-cast($n) default return $item }; declare function ejson:json-deserialize($serialized as item()?) as node()? { if (fn:empty($serialized)) then () else xdmp:to-json($serialized)/child::node() }; declare function ejson:json-encode($item as item()?) as item()* { typeswitch($item) case text() return $item case boolean-node() return $item case number-node() return $item case array-node() return $item case object-node() return $item default return let $t := ejson:type-of($item) return if ($t eq "string") then $item else if ($t eq "boolean") then boolean-node{$item} else ejson:json-encode-type($item) }; declare function ejson:json-encode-type($item as item()?) as object-node() { ejson:json-deserialize(let $t := ejson:type-of($item) return if (fn:empty($t)) then map:entry("_ejson.type", "na") else if ($t eq "null") then map:entry("_ejson.type", "null") else map:new((map:entry("_ejson.type", $t), map:entry("_ejson.value", $item)))) }; declare function ejson:json-is-array($item as item()?) as xs:boolean { typeswitch($item) case array-node() return fn:true() default return fn:false() }; declare function ejson:json-node-cast($node as node()?) as item()? { typeswitch($node) case $obj as object-node() return ejson:json-object-cast($obj) default return $node }; declare function ejson:json-node-type($node as node()) as xs:string? { typeswitch($node) case text() return "string" case null-node() return "null" case boolean-node() return "boolean" case number-node() return "decimal" case array-node() return "array" case $obj as object-node() return ejson:json-object-type($obj) default return () }; declare function ejson:json-object-cast($obj as object-node()) as item()* { let $t := ejson:json-object-type($obj), $v := map:get(xdmp:from-json($obj), "_ejson.value") return if ($t eq "timestamp") then xs:dateTime($v) else if ($t eq "date") then xs:date($v) else if ($t eq "time") then xs:time($v) else if ($t eq "interval") then xs:duration($v) else if ($t eq "integer") then xs:integer($v) else if ($t eq "decimal") then xs:double($v) else if ($t eq "id") then xs:string($v) else if ($t eq "null") then null-node{} else if ($t eq "na") then () else if ($t eq "binary") then if ($v castable as xs:hexBinary) then xs:base64Binary(xs:hexBinary($v)) else xs:base64Binary($v) else $obj }; declare function ejson:json-object-type($obj as object-node()) as xs:string { let $o := xdmp:from-json($obj) return if (map:contains($o, "_ejson.type")) then map:get($o, "_ejson.type") else "object" }; declare function ejson:seq-to-array($items as item()*) as node() { ejson:json-deserialize(json:to-array(fn:map(function($x) { ejson:json-encode($x) }, $items))) }; declare function ejson:type-of($item as item()*) as xs:string? { if (fn:empty($item)) then "na" else typeswitch($item) case $node as node() return ejson:json-node-type($node) case xs:boolean return "boolean" case xs:dateTime return "timestamp" case xs:date return "date" case xs:time return "time" case xs:duration return "interval" case xs:integer return "integer" case xs:decimal return "decimal" case xs:double return "decimal" case xs:float return "decimal" case xs:base64Binary return "binary" case xs:hexBinary return "binary" case xs:QName return "string" case xs:string return "string" case xs:untypedAtomic return "string" default return () }; declare function qscript:concat($x as item()?, $y as item()?) as item()? { let $xArr := ejson:json-is-array($x), $yArr := ejson:json-is-array($y) return if ($xArr and $yArr) then ejson:json-deserialize(json:to-array(($x/child::node(), $y/child::node()))) else if ($yArr) then ejson:json-deserialize(json:to-array((ejson:seq-to-array(qscript:to-char-seq($x))/child::node(), $y/child::node()))) else if ($xArr) then ejson:json-deserialize(json:to-array(($x/child::node(), ejson:seq-to-array(qscript:to-char-seq($y))/child::node()))) else fn:concat($x, $y) }; declare function qscript:to-char-seq($s as xs:string?) as xs:string* { fn:map(fn:codepoints-to-string#1, fn:string-to-codepoints($s)) }; for $n93 in let $n76 := "Unreferenced", $n77 := for $n79 in cts:search(fn:doc(), cts:document-query("/testDb/zips.json"), ("format-json"), 1.0, ())/child::node() let $n80 := $n79, $n81 := ejson:json-is-array($n80) for $n82 at $n84 in $n80/child::node() let $n83 := ejson:seq-to-array((if ($n81) then $n84 else fn:node-name($n82), $n82)) let $n85 := qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(1) + 1])))), ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(1) + 1])))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(()))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))), ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("city"))))), ejson:json-deserialize(json:to-array(ejson:json-encode(fn:matches((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("city"), "^.*springfield.*$", if (fn:true()) then "i" else ""))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(()))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("loc"))))), ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("loc"))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(()))))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))), ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("pop"))))), ejson:json-deserialize(json:to-array(ejson:json-encode(fn:matches((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("pop"), "^.*springfield.*$", if (fn:true()) then "i" else ""))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(()))))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))), ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(qscript:concat(qscript:concat(qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1])))))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:json-deserialize(json:to-array(ejson:json-encode($n83/child::node()[xs:integer(0) + 1]))))))), ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("state"))))), ejson:json-deserialize(json:to-array(ejson:json-encode(fn:matches((: GUARD CONT :)$n83/child::node()[xs:integer(1) + 1]/child::node("state"), "^.*springfield.*$", if (fn:true()) then "i" else ""))))))))), ejson:json-deserialize(json:to-array(ejson:json-encode(())))))))))))), $n86 := (: GUARD CONT :)$n85/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(3) + 1], $n87 := ejson:json-is-array($n86) for $n88 at $n90 in $n86/child::node() let $n89 := $n88 let $n91 := qscript:concat(ejson:json-deserialize(json:to-array(ejson:json-encode((: GUARD CONT :)$n85/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(3) + 1]))), ejson:json-deserialize(json:to-array(ejson:json-encode(ejson:cast-if-node(ejson:cast-if-node(ejson:cast-if-node((: GUARD CONT :)$n85/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(3) + 1]) or ejson:cast-if-node(fn:matches($n89, "^.*springfield.*$", if (fn:true()) then "i" else ""))) or ejson:cast-if-node((: GUARD CONT :)$n85/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(0) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(3) + 1])) or ejson:cast-if-node((: GUARD CONT :)$n85/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(1) + 1]/child::node()[xs:integer(3) + 1]))))) where xs:boolean($n91/child::node()[xs:integer(1) + 1]) return $n91, $n78 := for $n92 in "Unreferenced" return xs:integer(100) return fn:subsequence($n77, 1, $n78) return ejson:json-deserialize(map:new((map:entry("city", ejson:json-encode($n93/child::node()[xs:integer(0) + 1]/child::node("city"))), map:entry("loc", ejson:json-encode($n93/child::node()[xs:integer(0) + 1]/child::node("loc"))), map:entry("pop", ejson:json-encode($n93/child::node()[xs:integer(0) + 1]/child::node("pop"))), map:entry("state", ejson:json-encode($n93/child::node()[xs:integer(0) + 1]/child::node("state")))))) --- END QUERY ---
```

<img width="839" alt="screen shot 2017-06-16 at 09 00 22" src="https://user-images.githubusercontent.com/3036557/27217925-dad0934e-5273-11e7-9649-48d30e6d1adc.png">

this issue is ported from https://github.com/slamdata/slamdata/issues/1857 by request

**Comment by wemrysi** [comment] 2017-06-20 15:38
This appears to be due to the lack of runtime typecheck support in the MarkLogic connector (#1506) and should be fixed when that feature is implemented.

**Comment by jsantos17** [comment] 2017-07-12 20:38
Closing as duplicate of #1506. This works fine on marklogic_xml, due to a (lucky) cast Marklogic does on sequences of `element` to `string`. With `object`, Marklogic does not coerce the sequence of objects to string and instead throws an exception.

**Closed by jsantos17** 2017-07-12 20:38 UTC
Labels: topic: MarkLogic
