### ISSUE TITLE
Query executed with mapReduce instead of aggregate and lookup

### ISSUE THREAD

**Issue by gbenshim** [quasar-analytics/quasar#1896] opened 2017-02-07 21:38 UTC
I run the following sql:

select tp._id, count(*)
from `/tpdb/test/testPrograms` as tp 
join `/tpdb/test/testInstances` as ti 
on tp._id = ti.TestProgramId 
group by tp._id

From the logs i can see that its preforming map-reduce.
Its taking forever, using REST Api from C# code I get timeout exception.

I run this query directly on the database:
db.testPrograms.aggregate(
[    
    { $lookup: { from: "testInstances", localField: "_id", foreignField: "TestProgramId", as: "instances"} },
    { $project: {"_id":1, instancesCount: {$size: "$instances"} } }
])

The query does the same, finishes in less than a second.

I verified there's an index on testInstances.TestProgramId.
Sql query should finish in no time.

Please help

Gili

**Comment by sellout** [comment] 2017-02-07 22:04
Duplicate of #1895.

However, this also points out that we don’t yet take advantage of the `$size` expression.

**Comment by alissapajer** [comment] 2017-03-06 17:42
Since #1895 has been closed, I'm closing this issue. @sellout do you want to make another ticket about the `$size` expression?

**Closed by alissapajer** 2017-03-06 17:42 UTC

**Comment by zeeiyerWork** [comment] 2017-04-21 23:59
@sellout -> did you create another issue for $size expression - and reference that here?
