### ISSUE TITLE
Getting error Quasar error: quasar.Predef$.coenvTraverse

### ISSUE THREAD

**Issue by SathishRaju** [quasar-analytics/quasar#1280] opened 2016-07-25 09:19 UTC
I can able to connect to REPL with the latest released JAR. Can list the dbs in my MongoDB. But when running query got the error below:

💪 $ select \* from users
Quasar error: quasar.Predef$.coenvTraverse(Lscalaz/Traverse;)Lscalaz/Traverse;

I even tried this in various other OSes (Ubuntu, Mac, Fedora). Same error.

**Comment by jedesah** [comment] 2016-12-29 23:46
@SathishRaju Is this still an issue?

**Comment by zeeiyerWork** [comment] 2017-05-12 18:14
@jedesah -> Please try and recreate and if not possible to reproduce, then close it, since we have not heard from @SathishRaju for 5 months.

**Comment by alissapajer** [comment] 2017-06-21 15:29
There is not enough information provided to reproduce this issue so I am closing it.

**Closed by alissapajer** 2017-06-21 15:29 UTC
Labels: epic: REPL Issues
