### ISSUE TITLE
Getting 500 error when chaining multiple :results queries

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#3054] opened 2017-11-08 23:02 UTC
Although this is happening in SlamData, I believe it to be a quasar issue on the backend. Happy to move to another repo. @jedesah and @djspiewak provided some comments in Slack [here](https://slamdata.slack.com/archives/C09MRGSHW/p1510030218000123) about possibilities.

Here is the general order of cards, one query feeding into the next:

Query 1 in Markdown:

```
gateway = {!``SELECT DISTINCT(name) FROM `/wg/emclab/gateways` ORDER BY description ASC``}
```

User selects a gateway, then this query launches for another Markdown:

Query 2:

```
device={!``SELECT DISTINCT(devices.name) AS name FROM `/wg/emclab/gateways` AS gateways JOIN `/wg/emclab/devices` AS devices ON gateways.id = devices.parent_id WHERE gateways.name = :gateway ORDER BY devices.name ASC``}
```

User selects the device, then this query launches for another Markdown:

Query 3:

```
readings = [!``SELECT DISTINCT(devices.fields{*}) as fieldname FROM `/wg/emclab/devices` AS devices WHERE devices.name = :device LIMIT 0 ``]
!``SELECT DISTINCT(devices.fields{*:}) as fieldname FROM `/wg/emclab/devices` AS devices WHERE devices.name = :device``
```

User selects the fields they wish to report on, then the following queries launch in sequential order, each on their own card. This approach was needed since we're allowing users to select gateways and devices by name, but they're actually referenced internally via id's

Query 4:

```
SELECT
    gateways.id AS id1
FROM `/wg/emclab/gateways` AS gateways
WHERE
    gateways.name = :gateway
```

Query 5:

```
SELECT
    devices.id as devid
FROM
    :results AS r,
    `/wg/emclab/devices` AS devices
WHERE
    devices.parent_id = r.`id1` AND
    devices.name = :device
```

Query 6:

```
SELECT
    datasets.id as dsid
FROM
    :results AS r,
    `/wg/emclab/datasets` AS datasets
WHERE
   datasets.device_id = r.devid
```

Here is the Chrome HAR file I exported when running it. It shows the 500 error and the network activity.

[500-error.har.zip](https://github.com/quasar-analytics/quasar/files/1455708/500-error.har.zip)

**Comment by damonLL** [comment] 2017-11-08 23:03
Also: no text or error message accompanies the 500, just the 500 itself.

**Comment by zeeiyerWork** [comment] 2017-11-09 00:17
This has been added to November iteration and "skulled" - since it is blocking a POC for a prospect (details available offline). It could be what @djspiewak conjectured offline -> "if you use a zillion chained `:results`, and there is no caching in play (reminder: caching is automatically disabled if you have any variables other than `:results`), then it can generate queries which are absurdly nested.  Those queries can cause problems for current master (QSU should fix this)."..... So it seems we should re-evaluate to see if this query stays pathological after QSU work and proceed from there.

**Comment by djspiewak** [comment] 2017-11-09 08:56
Assuming this is failing where I think it is (btw three definitely isn’t a zillion, though there are variables), then QSU will help things a lot.

**Comment by damonLL** [comment] 2017-11-13 20:37
[Here](https://drive.google.com/a/slamdata.com/file/d/11HSFhaCXnfEB4qgunynsEU0C1oES6yS8/view?usp=sharing) are the related collections, downloaded from MongoDB via SlamData UI.

**Comment by zeeiyerWork** [comment] 2017-11-13 23:02
Thanks @damonLL - seems like the next step is to re-evaluate post QSU to merge to Master.

**Comment by djspiewak** [comment] 2017-11-23 22:36
@damonLL QSU has now been merged to master.  Can you reevaluate when convenient?

**Comment by djspiewak** [comment] 2017-12-04 20:56
I'm going to provisionally close this, since @damonLL reported a week ago that he wasn't able to reproduce it anymore.

**Closed by djspiewak** 2017-12-04 20:56 UTC
Labels: source: Customer, type: Bug, ☠️
