### ISSUE TITLE
Error requesting a mount

### ISSUE THREAD

**Issue by jonsterling** [quasar-analytics/quasar#869] opened 2015-08-13 17:57 UTC
If I configure SlamEngine with a single mount at `/welp`, and then I open SlamData and try to configure that mount (by pressing the wrench icon), nothing happens; in the console, I see the following error from slamengine: `There is no mount point at /welp/`.

Is this a bug, or did I do something wrong?

The failing request was a `GET` to `http://localhost:8080/mount/fs//welp/`.

My configuration is as follows:

````
{
    "mountings": {
        "/welp": {
            "mongodb": {
                "connectionUri": "[redacted]"
            }
        }
    },
    "server": { "port": 8080 }
}
```

**Comment by garyb** [comment] 2015-08-13 18:06
I think this is because in the config it should be listed as `/welp/` (needs the trailing slash).

Not sure whether that's considered a bug or not, I thought we ensured it had the trailing slash when mounting via the API.

**Comment by mossprescott** [comment] 2015-08-13 18:07
The mount path _must_ end with a `/`. The API now enforces this requirement by giving an error when a mount is added, but if you edit the file manually you can get it into an invalid state like this. The fix is just to add a trailing slash to each mount path.

On the other hand, the backend normalizes paths so that you can still see the contents of this mount at the path `/welp/`. We decided this was better than just ignoring the mount.

This situation can be confusing and there may be a better way to handle it. The simplest idea might be to reflect the normalized paths in the `mount` API as well.

**Comment by jonsterling** [comment] 2015-08-13 18:09
@mossprescott @garyb Thanks very much for your help!

Do we expect customers to ever edit the config file manually? If not, then I think it is probably fine to close this ticket.

**Comment by sellout** [comment] 2015-08-13 18:16
We don’t expect customers to edit the config manually. However … we also want to modify the config format & data structure, which will eliminate this problem as well as problems like having mounts defined at both `/foo/` and `/foo/bar/baz`.

However, we don’t seem to have an issue open for that … should we keep this one?

**Comment by jonsterling** [comment] 2015-08-13 18:17
@sellout OK, makes sense. Thanks everyone! Feel free to either close or repurpose this issue...

**Comment by jdegoes** [comment] 2015-08-13 18:30
SlamEngine should be able to recover from invalid config or at least prevent startup with a useful message. Failing silently and then doing the wrong thing is not acceptable. So I'll leave this ticket open.

**Comment by mossprescott** [comment] 2015-08-13 18:36
@jdegoes: Unless we have an idea what we're doing here, I suggest we remove it from ASAP.

**Comment by jdegoes** [comment] 2015-08-13 18:51
I'll bump it to 2.3, but the problem described by this ticket is that it's possible to get SlamEngine into a weird state where it claims something is a mount and the mount API refuses to acknowledge it as one. If the cause is invalid config, the solution is rejecting the config or normalizing it.

**Comment by mossprescott** [comment] 2015-08-13 19:25
What would rejecting invalid config look like? The server could validate the config and exit with a non-zero exit code, but I don't think the bundled app would be able to do anything with that at the moment, since there would be no page to point a browser at in that case.

Normalizing it sounds like a better idea. Some things it will need to account for:
- Normalization is backend-dependent (e.g. MongoDB mounts always live at directory paths, but others might not).
- Multiple mount paths that normalize to the same path (e.g. MongoDB mounts at `/foo` and `/foo/`).
- Resolving conflicting mount paths found in the config file (e.g. a mount at `/foo` follwed by

**Closed** 2015-12-11 16:43 UTC
Labels: bug
