### ISSUE TITLE
ERROR Query decoding Long failed when retrieving long string of numeric digits

### ISSUE THREAD

**Issue by drmikecrowe** [quasar-analytics/quasar#1894] opened 2017-02-05 15:56 UTC
We have a long numeric string in our collection (20-digits).

This simple query:

    SELECT TO_STRING(item) 
    FROM `/db/items`

gives this error message:
    
    invalid offset: Query decoding Long failed 

Data looks like:

    {
        "_id" : ObjectId("5890854b11f830001c75a72c"),
        "item" : "11111111111111110154"
    }

**Comment by jdegoes** [comment] 2017-02-07 03:14
Can you report version of MongoDB being used?

**Comment by drmikecrowe** [comment] 2017-02-07 14:45
Apologies:

* quasar-web-assembly-14.5.2.jar
* MongoDB:
    * "version" : "3.2.11",
    * "gitVersion" : "009580ad490190ba33d1c6253ebd8d91808923e4"

**Comment by sellout** [comment] 2017-03-13 21:35
@drmikecrowe In your data example `"item"` is a String. It’s fine to call `TO_STRING` on a String, but I wonder if `"item"` is actually stored differently, because I’m not sure how we could get “decoding Long failed” otherwise.

**Comment by drmikecrowe** [comment] 2017-03-15 16:00
@sellout I'm 100% positive it's stored as a string in Mongo

**Comment by drmikecrowe** [comment] 2017-03-15 16:02
@sellout  I'm 100% positive it's stored as a string.  If you like, I can email you and example (the actual data is a sensitive item, so I'd rather not post it here if possible)

**Comment by zeeiyerWork** [comment] 2017-05-12 18:16
@sellout - don't see further conversations with @drmikecrowe - if this is resolved in the new mongo connector, please let us know.

**Comment by jsantos17** [comment] 2017-08-16 17:20
@zeeiyerWork confirmed as fixed in new Mongo. 

```
> db.issue1894.find({})
{ "_id" : ObjectId("59947bafd9eb01664b5289e9"), "item" : "11111111111111110154" }
```

Then:

```sql
SELECT TO_STRING(item) FROM `/mngo/jps/issue1894`
```

works correctly and yields `{ "value": "11111111111111110154" }`

**Comment by jsantos17** [comment] 2017-09-08 16:58
Confirmed as fixed in new Mongo

**Closed by jsantos17** 2017-09-08 16:58 UTC
Labels: epic: Miscellaneous Quasar Issues, status: Fixed in New Mongo, status: In review, type: Bug
