### ISSUE TITLE
AVG function with WHERE clause appears to confuse MarkLogic

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1698] opened 2016-11-14 00:01 UTC
This may be premature considering @wemrysi isn't 100% complete with the connector, but I thought I would start logging some of the issues.  This is with latest quasar/master Nov 13th, version 13.0.30

This query works:

```
select AVG(age) from patients
```

This query does not work:

```
select AVG(age) from patients where city = "AUSTIN"
```

Returns long error message, attached as file.

[marklogic-avg-where.txt](https://github.com/quasar-analytics/quasar/files/588179/marklogic-avg-where.txt)

**Comment by wemrysi** [comment] 2016-11-18 19:03
I am unable to reproduce this on the current `master` so looks like it was fixed at some point since reporting, closing.

Via the repl:
```
$ select avg(age) from patients where city = "AUSTIN"
<plan output elided>
Query time: 8.3s
{ "_0": 71.6666666666667 }
```
Also, the output you saw isn't an error message, it is the physical plan (i.e. the XQuery that your query compiled to) for whatever backend you're querying.

**Closed by wemrysi** 2016-11-18 19:03 UTC
Labels: bug, MarkLogic
