### ISSUE TITLE
Inconsistent delete behavior at file system root

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1276] opened 2016-07-21 20:12 UTC
I have a DB mounted at `/`. Deleting a non-existent file at the root yields a `204 No Content`. Deleting a non-existent file inside a folder yields a `404 Not Found`.

**Comment by jedesah** [comment] 2017-01-03 20:41
@natefaubion What DB were you using? MongoDB doesn't permit to have top-level files, so it's not possible to reproduce this problem with it. You just get an "invalid path" error.

I was able to reproduce this error with MarkLogic and it would appear as a first guess that it might be a bug with the MarkLogic implementation where the file doesn't actually get deleted even though it doesn't show up in the metadata anymore. I say that because I was only able to trigger this response by trying to delete a file that had previously existed, but no longer did. As opposed to a file that never existed in the first place.

If you confirm you were on MarkLogic then my hypothesis seems likely, if not, I'll try and reproduce with the DB you were using and see if that yields any new insight.

**Comment by jsantos17** [comment] 2017-06-15 23:59
I tried to reproduce this issue with Marklogic and failed. Even with @jedesah's suggestion that it only happens with files that once existed. With a database mounted at `/`

1. Create a file at the root

```
curl -vv 'http://localhost:20223/data/fs/testBug' -X PUT -H 'Content-Type: application/json;mode=readable' --data-binary '[{}]'
```

Quasar responds as expected with 200 OK

2. Delete the file

```
curl -vv -X DELETE http://localhost:20223/data/fs/testBug
```

Quasar responds as expected with 204 No Content

3. Try to delete again

```
curl -vv -X DELETE http://localhost:20223/data/fs/testBug
```

Quasar responds as expected with 404 Not Found


Similar results with a file within a directory. Tomorrow I'll try with a commit before #2273 was merged and see if that fixed it.

**Comment by jsantos17** [comment] 2017-06-16 20:22
@natefaubion What database were you using? Was it Marklogic?

**Comment by jsantos17** [comment] 2017-06-19 18:09
@zeeiyerWork I have tried unsuccessfully to reproduce this. This is almost one year old and it seems like nobody has hit it. I also understand the Marklogic connector has undergone significant changes. Because of this, I think we should close this. What do you think?

**Comment by zeeiyerWork** [comment] 2017-06-20 00:50
@jsantos17 -> lets close this as not reproducible. I agree that ML connector is completely redone - so this old issue, perhaps does not apply and you have verified that by trying to recreate it without success.

**Comment by jsantos17** [comment] 2017-06-20 14:45
Closing as not reproducible.

**Closed by jsantos17** 2017-06-20 14:45 UTC
Labels: epic: Miscellaneous Quasar Issues, type: Bug
