### ISSUE TITLE
'Create folder' errors for marklogic and couchbase in http interface

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#1986] opened 2017-03-20 18:54 UTC
In the couchbase mount, when I click on 'Create folder' I get the error:
```
There was a problem creating the directory: Resource not found
```
In the marklogic mount, when I click on 'Create folder' I get the error:
```
There was a problem creating the directory: An unknown error ocurred: 500 "{ \"error\": { \"status\": \"Error persisting uploaded data.\", \"detail\": { \"errors\": [ { \"status\": \"Failed to write data.\", \"detail\": { \"message\": \"Failed to write data: Malformed content URI: /Untitled Folder/temp-dzqCn7oqIf/11e70d9e4c9a65448141fa2ea4c03a59.\", \"data\": { } } } ] } } }"
```
I haven't tested 'Create folder' for spark. It succeeds for mongo.

**Comment by alissapajer** [comment] 2017-03-20 18:55
Oh, I should probably put this bug report in the slamdata repo.

**Comment by drostron** [comment] 2017-03-20 18:59
@alissapajer Is this a root folder within a CB mount? If so, that isn't currently supported. #1740 will address it.

**Comment by alissapajer** [comment] 2017-03-20 19:11
@drostron Yes it's a root folder within a CB mount. If I try to make a folder inside `beer-sample`, for example, that succeeds.

**Comment by drostron** [comment] 2017-03-20 19:13
@alissapajer Ok, then yes, that failure is currently expected. The error message is unfortunately opaque and not helpful.

**Comment by jsantos17** [comment] 2017-06-17 00:22
I was unable to reproduce this issue with Marklogic. I believe the frontend has changed the way it creates new folder since I don't see requests similar to the ones in the issue description. However, I did try your request but Quasar returns 200, no matter how much I try to make it fail

```
curl -vvv 'http://localhost:20223/data/fs/Untitled%20Folder/temp-dzqCn7oqIf/11e70d9e4c9a65448141fa2ea4c03a59.' -X PUT  -H 'Content-Type: application/json;mode=readable' --data-binary '[{}]'
```

Is there something missing in my request?

 Would you mind helping me reproduce this on Monday (June 19th) @alissapajer?

**Comment by alissapajer** [comment] 2017-06-20 19:35
@jsantos17 I just tested this against quasar 18.5.0 and slamdata v4.2.2-qa-prerelease-7 and I was unable to reproduce. I successfully created new folders in marklogic (xml and json), couchbase, mongo, and spark. 

So this can be closed as no longer reproducible.

**Comment by jsantos17** [comment] 2017-06-20 19:37
@zeeiyerWork closing this as not reproducible.

**Closed by jsantos17** 2017-06-20 19:37 UTC
Labels: epic: Connector: Marklogic Overhaul, topic: MarkLogic, type: Bug
