### ISSUE TITLE
Subselect in WHERE clause doesn't work

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1470] opened 2016-09-26 19:36 UTC
At @jdegoes's direction, closed [SlamData Issue #1048](https://github.com/slamdata/slamdata/issues/1048) and reopening here.  Initial summary below:

<hr>

The following query:

```
SELECT * FROM `/devguide/devdb/patients` AS p
WHERE state IN (SELECT state FROM `/devguide/devdb/states`)
```

gives the error:

```
An unknown error ocurred: 500 "{ \"error\": { \"status\": \"Unsupported function.\",
\"detail\":{ \"message\": \"The function 'WHERE' is recognized but not supported
by this back-end. (in JS planner)\", \"functionName\": \"WHERE\", \"logicalPlan\": {
....
```

Current usable workaround provided by @sellout:

```
SELECT p.* FROM `/devguide/devdb/patients` AS p
INNER JOIN `/devguide/devdb/states` AS s
ON p.state = s.state
```

**Comment by zeeiyerWork** [comment] 2017-03-22 00:24
Maybe this just goes away with the new Mongo Connector - so we just need to check that !

**Comment by nicflores** [comment] 2017-04-11 23:08
I spoke with @sellout today about this error and after some effort to reproduce we realized the following:

1. In old mongo we are now seeing this error:
```
💪 $ SELECT * FROM `/mongo/test/patients10` AS p WHERE state IN (SELECT state FROM `/mongo/test/zips`)
Quasar error: Plan execution failed: MongoDB Error: Command failed with error 16722: 'exception: TypeError: Object [object Object] has no method 'indexOf'
    at _funcs1 (_funcs1:1:44) near '!== this.indexOf(thi' ' on server 192.168.99.101:27019. The full response is { "errmsg" : "exception: TypeError: Object [object Object] has no method 'indexOf'\n    at _funcs1 (_funcs1:1:44) near '!== this.indexOf(thi' ", "code" : 16722, "ok" : 0.0 }, cause=Some(Command failed with error 16722: 'exception: TypeError: Object [object Object] has no method 'indexOf'
    at _funcs1 (_funcs1:1:44) near '!== this.indexOf(thi' ' on server 192.168.99.101:27019. The full response is { "errmsg" : "exception: TypeError: Object [object Object] has no method 'indexOf'\n    at _funcs1 (_funcs1:1:44) near '!== this.indexOf(thi' ", "code" : 16722, "ok" : 0.0 })
``` 

this error is actually further along in the execution process than what @damonLL reports. So something has been fixed since the issue was created that pushes Damon's query along a little further. In this case the error above comes from mongo whereas Damon's error comes from the `LogicalPlanner`.

2. In new mongo we get an entirely different error:
```
💪 $ SELECT * FROM `/mongoq/test/patients10` AS p WHERE state IN (SELECT state FROM `/mongoq/test/zips`)
Quasar error: couldn’t merge array
```
which upon further inspection using `debug=2` shows some multi `EquiJoin`s:

```
QScript (Mongo-specific):
Map
├─ Subset(Take)
│  ├─ Unreferenced
│  ├─ From
│  │  ╰─ Filter
│  │     ├─ EquiJoin
│  │     │  ├─ Unreferenced
│  │     │  ├─ ShiftedRead(ShiftedRead(/test/patients10, IncludeId))
│  │     │  ├─ EquiJoin
│  │     │  │  ├─ Unreferenced
│  │     │  │  ├─ Map
...
```

It is likely that once #1943 and #1929 are complete this error may be fixed in new mongo.

I suggest that we re-evaluate this ticket once the two tickets above are resolved. If we still bump into this error then we can continue debugging using the queries posted in this comment and by Damon.

@zeeiyerWork, maybe we punt this issue out to a future milestone after the two issues above are completed? Let me know if that's ok with you.

**Comment by alissapajer** [comment] 2017-04-11 23:14
Agreed that any join-related qscript issues should be re-evaluated after #1943 (new LP joins) and #1929 (qscript provenance issue) land.

**Comment by zeeiyerWork** [comment] 2017-07-10 21:10
@nicflores -> @sellout advises to try this again. 
#1943  is fixed.

**Comment by nicflores** [comment] 2017-07-14 04:42
Running the above query in the new-mongo branch I'm now seeing a similar error that Doug reports in #2466.
query:
```
💪 $ SELECT * FROM `/mongo/testdata/patients.data` AS p WHERE state IN (SELECT state FROM `/mongo/testdata/zips`)
```

```
Quasar error: Plan execution failed: MongoDB Error: Command failed with error 13070: 'exception: value too large to reduce' on server 192.168.99.100:27019. The full response is { "errmsg" : "exception: value too large to reduce", "code" : 13070, "ok" : 0.0 }, cause=Some(Command failed with error 13070: 'exception: value too large to reduce' on server 192.168.99.100:27019. The full response is { "errmsg" : "exception: value too large to reduce", "code" : 13070, "ok" : 0.0 })
```

Here's the Qscript that was generated:
```
QScript (Mongo-specific):
Map
├─ Filter
│  ├─ EquiJoin
│  │  ├─ Unreferenced
│  │  ├─ ShiftedRead(/testdata/patients.data, ExcludeId)
│  │  ├─ EquiJoin
│  │  │  ├─ Unreferenced
│  │  │  ├─ Map
│  │  │  │  ├─ ShiftedRead(/testdata/patients.data, IncludeId)
│  │  │  │  ╰─ ConcatArrays
│  │  │  │     ├─ ConcatArrays
│  │  │  │     │  ├─ MakeArray
│  │  │  │     │  │  ╰─ MakeArray
│  │  │  │     │  │     ╰─ ProjectIndex
│  │  │  │     │  │        ├─ ○
│  │  │  │     │  │        ╰─ Constant(Int(0))
│  │  │  │     │  ╰─ MakeArray
│  │  │  │     │     ╰─ ProjectIndex
│  │  │  │     │        ├─ ○
│  │  │  │     │        ╰─ Constant(Int(1))
│  │  │  │     ╰─ MakeArray
│  │  │  │        ╰─ ProjectIndex
│  │  │  │           ├─ ○
│  │  │  │           ╰─ Constant(Int(1))
│  │  │  ├─ Reduce
│  │  │  │  ├─ ShiftedRead(/testdata/zips, ExcludeId)
│  │  │  │  ├─ Bucket
│  │  │  │  │  ╰─ List
│  │  │  │  ├─ Reducers
│  │  │  │  │  ╰─ UnshiftArray
│  │  │  │  │     ╰─ Guard
│  │  │  │  │        ├─ ○
│  │  │  │  │        ├─ Type(Obj(Map[], Some(Top)))
│  │  │  │  │        ├─ ProjectField
│  │  │  │  │        │  ├─ ○
│  │  │  │  │        │  ╰─ Constant(Str(state))
│  │  │  │  │        ╰─ Undefined
│  │  │  │  ╰─ Repair
│  │  │  │     ╰─ ReduceIndex(\/-(0))
│  │  │  ├─ List
│  │  │  ├─ Inner
│  │  │  ╰─ ConcatArrays
│  │  │     ├─ MakeArray
│  │  │     │  ╰─ LeftSide
│  │  │     ╰─ MakeArray
│  │  │        ╰─ RightSide
│  │  ├─ List
│  │  ├─ Inner
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ ConcatArrays
│  │     │     ├─ MakeArray
│  │     │     │  ╰─ LeftSide
│  │     │     ╰─ MakeArray
│  │     │        ╰─ LeftSide
│  │     ╰─ MakeArray
│  │        ╰─ ConcatArrays
│  │           ├─ ConcatArrays
│  │           │  ├─ ConcatArrays
│  │           │  │  ├─ MakeArray
│  │           │  │  │  ╰─ MakeArray
│  │           │  │  │     ╰─ ProjectIndex
│  │           │  │  │        ├─ ProjectIndex
│  │           │  │  │        │  ├─ ProjectIndex
│  │           │  │  │        │  │  ├─ RightSide
│  │           │  │  │        │  │  ╰─ Constant(Int(0))
│  │           │  │  │        │  ╰─ Constant(Int(0))
│  │           │  │  │        ╰─ Constant(Int(0))
│  │           │  │  ╰─ MakeArray
│  │           │  │     ╰─ ConcatArrays
│  │           │  │        ├─ MakeArray
│  │           │  │        │  ╰─ ProjectIndex
│  │           │  │        │     ├─ ProjectIndex
│  │           │  │        │     │  ├─ ProjectIndex
│  │           │  │        │     │  │  ├─ RightSide
│  │           │  │        │     │  │  ╰─ Constant(Int(1))
│  │           │  │        │     │  ╰─ Constant(Int(0))
│  │           │  │        │     ╰─ Constant(Int(0))
│  │           │  │        ╰─ MakeArray
│  │           │  │           ╰─ ProjectIndex
│  │           │  │              ├─ ProjectIndex
│  │           │  │              │  ├─ ProjectIndex
│  │           │  │              │  │  ├─ RightSide
│  │           │  │              │  │  ╰─ Constant(Int(1))
│  │           │  │              │  ╰─ Constant(Int(1))
│  │           │  │              ╰─ Constant(Int(0))
│  │           │  ╰─ MakeArray
│  │           │     ╰─ Guard
│  │           │        ├─ ProjectIndex
│  │           │        │  ├─ ProjectIndex
│  │           │        │  │  ├─ RightSide
│  │           │        │  │  ╰─ Constant(Int(0))
│  │           │        │  ╰─ Constant(Int(1))
│  │           │        ├─ Type(Obj(Map[], Some(Top)))
│  │           │        ├─ ProjectField
│  │           │        │  ├─ ProjectIndex
│  │           │        │  │  ├─ ProjectIndex
│  │           │        │  │  │  ├─ RightSide
│  │           │        │  │  │  ╰─ Constant(Int(0))
│  │           │        │  │  ╰─ Constant(Int(2))
│  │           │        │  ╰─ Constant(Str(state))
│  │           │        ╰─ Undefined
│  │           ╰─ MakeArray
│  │              ╰─ ProjectIndex
│  │                 ├─ RightSide
│  │                 ╰─ Constant(Int(1))
│  ╰─ And
│     ├─ Constant(Bool(true))
│     ╰─ Within
│        ├─ ProjectIndex
│        │  ├─ ProjectIndex
│        │  │  ├─ ○
│        │  │  ╰─ Constant(Int(1))
│        │  ╰─ Constant(Int(2))
│        ╰─ ProjectIndex
│           ├─ ProjectIndex
│           │  ├─ ○
│           │  ╰─ Constant(Int(1))
│           ╰─ Constant(Int(3))
╰─ Guard
   ├─ ProjectIndex
   │  ├─ ProjectIndex
   │  │  ├─ ○
   │  │  ╰─ Constant(Int(0))
   │  ╰─ Constant(Int(0))
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ ProjectIndex
   │  ├─ ProjectIndex
   │  │  ├─ ○
   │  │  ╰─ Constant(Int(0))
   │  ╰─ Constant(Int(1))
   ╰─ Undefined
```

**Comment by nicflores** [comment] 2017-07-14 22:22
Running the same query in couchbase gives a different error:
```
💪 $ SELECT * FROM `/cb/patients.data` AS p WHERE state IN (SELECT state FROM `/cb/zips`)
QScript (Optimized):
Map
├─ Subset(Take)
│  ├─ Unreferenced
│  ├─ From
│  │  ╰─ Filter
│  │     ├─ EquiJoin
│  │     │  ├─ Unreferenced
│  │     │  ├─ ShiftedRead(/patients.data, ExcludeId)
│  │     │  ├─ EquiJoin
│  │     │  │  ├─ Unreferenced
│  │     │  │  ├─ Map
│  │     │  │  │  ├─ ShiftedRead(/patients.data, IncludeId)
│  │     │  │  │  ╰─ ConcatArrays
│  │     │  │  │     ├─ ConcatArrays
│  │     │  │  │     │  ├─ MakeArray
│  │     │  │  │     │  │  ╰─ MakeArray
│  │     │  │  │     │  │     ╰─ ProjectIndex
│  │     │  │  │     │  │        ├─ ○
│  │     │  │  │     │  │        ╰─ Constant(Int(0))
│  │     │  │  │     │  ╰─ MakeArray
│  │     │  │  │     │     ╰─ ProjectIndex
│  │     │  │  │     │        ├─ ○
│  │     │  │  │     │        ╰─ Constant(Int(1))
│  │     │  │  │     ╰─ MakeArray
│  │     │  │  │        ╰─ ProjectIndex
│  │     │  │  │           ├─ ○
│  │     │  │  │           ╰─ Constant(Int(1))
│  │     │  │  ├─ Reduce
│  │     │  │  │  ├─ ShiftedRead(/zips, ExcludeId)
│  │     │  │  │  ├─ Bucket
│  │     │  │  │  │  ╰─ List
│  │     │  │  │  ├─ Reducers
│  │     │  │  │  │  ╰─ UnshiftArray
│  │     │  │  │  │     ╰─ Guard
│  │     │  │  │  │        ├─ ○
│  │     │  │  │  │        ├─ Type(Obj(Map[], Some(Top)))
│  │     │  │  │  │        ├─ ProjectField
│  │     │  │  │  │        │  ├─ ○
│  │     │  │  │  │        │  ╰─ Constant(Str(state))
│  │     │  │  │  │        ╰─ Undefined
│  │     │  │  │  ╰─ Repair
│  │     │  │  │     ╰─ ReduceIndex(\/-(0))
│  │     │  │  ├─ List
│  │     │  │  ├─ Inner
│  │     │  │  ╰─ ConcatArrays
│  │     │  │     ├─ MakeArray
│  │     │  │     │  ╰─ LeftSide
│  │     │  │     ╰─ MakeArray
│  │     │  │        ╰─ RightSide
│  │     │  ├─ List
│  │     │  ├─ Inner
│  │     │  ╰─ ConcatArrays
│  │     │     ├─ MakeArray
│  │     │     │  ╰─ ConcatArrays
│  │     │     │     ├─ MakeArray
│  │     │     │     │  ╰─ LeftSide
│  │     │     │     ╰─ MakeArray
│  │     │     │        ╰─ LeftSide
│  │     │     ╰─ MakeArray
│  │     │        ╰─ ConcatArrays
│  │     │           ├─ ConcatArrays
│  │     │           │  ├─ ConcatArrays
│  │     │           │  │  ├─ MakeArray
│  │     │           │  │  │  ╰─ MakeArray
│  │     │           │  │  │     ╰─ ProjectIndex
│  │     │           │  │  │        ├─ ProjectIndex
│  │     │           │  │  │        │  ├─ ProjectIndex
│  │     │           │  │  │        │  │  ├─ RightSide
│  │     │           │  │  │        │  │  ╰─ Constant(Int(0))
│  │     │           │  │  │        │  ╰─ Constant(Int(0))
│  │     │           │  │  │        ╰─ Constant(Int(0))
│  │     │           │  │  ╰─ MakeArray
│  │     │           │  │     ╰─ ConcatArrays
│  │     │           │  │        ├─ MakeArray
│  │     │           │  │        │  ╰─ ProjectIndex
│  │     │           │  │        │     ├─ ProjectIndex
│  │     │           │  │        │     │  ├─ ProjectIndex
│  │     │           │  │        │     │  │  ├─ RightSide
│  │     │           │  │        │     │  │  ╰─ Constant(Int(1))
│  │     │           │  │        │     │  ╰─ Constant(Int(0))
│  │     │           │  │        │     ╰─ Constant(Int(0))
│  │     │           │  │        ╰─ MakeArray
│  │     │           │  │           ╰─ ProjectIndex
│  │     │           │  │              ├─ ProjectIndex
│  │     │           │  │              │  ├─ ProjectIndex
│  │     │           │  │              │  │  ├─ RightSide
│  │     │           │  │              │  │  ╰─ Constant(Int(1))
│  │     │           │  │              │  ╰─ Constant(Int(1))
│  │     │           │  │              ╰─ Constant(Int(0))
│  │     │           │  ╰─ MakeArray
│  │     │           │     ╰─ Guard
│  │     │           │        ├─ ProjectIndex
│  │     │           │        │  ├─ ProjectIndex
│  │     │           │        │  │  ├─ RightSide
│  │     │           │        │  │  ╰─ Constant(Int(0))
│  │     │           │        │  ╰─ Constant(Int(1))
│  │     │           │        ├─ Type(Obj(Map[], Some(Top)))
│  │     │           │        ├─ ProjectField
│  │     │           │        │  ├─ ProjectIndex
│  │     │           │        │  │  ├─ ProjectIndex
│  │     │           │        │  │  │  ├─ RightSide
│  │     │           │        │  │  │  ╰─ Constant(Int(0))
│  │     │           │        │  │  ╰─ Constant(Int(2))
│  │     │           │        │  ╰─ Constant(Str(state))
│  │     │           │        ╰─ Undefined
│  │     │           ╰─ MakeArray
│  │     │              ╰─ ProjectIndex
│  │     │                 ├─ RightSide
│  │     │                 ╰─ Constant(Int(1))
│  │     ╰─ And
│  │        ├─ Constant(Bool(true))
│  │        ╰─ Within
│  │           ├─ ProjectIndex
│  │           │  ├─ ProjectIndex
│  │           │  │  ├─ ○
│  │           │  │  ╰─ Constant(Int(1))
│  │           │  ╰─ Constant(Int(2))
│  │           ╰─ ProjectIndex
│  │              ├─ ProjectIndex
│  │              │  ├─ ○
│  │              │  ╰─ Constant(Int(1))
│  │              ╰─ Constant(Int(3))
│  ╰─ Count
│     ╰─ Map
│        ├─ Unreferenced
│        ╰─ Constant(Int(11))
╰─ Guard
   ├─ ProjectIndex
   │  ├─ ProjectIndex
   │  │  ├─ ○
   │  │  ╰─ Constant(Int(0))
   │  ╰─ Constant(Int(0))
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ ProjectIndex
   │  ├─ ProjectIndex
   │  │  ├─ ○
   │  │  ╰─ Constant(Int(0))
   │  ╰─ Constant(Int(1))
   ╰─ Undefined

Quasar error: unimplemented EquiJoin: Not currently mapped to N1QL's key join
```

**Comment by alissapajer** [comment] 2017-07-14 22:28
@nicflores so couchbase only implements key-joins, so basically any qscript that contains a join will return that error in couchbase unless the query was of a specific type. (See `it/src/main/resources/tests/couchbase/` for examples of joins that will work in couchbase.) 

Both marklogic and spark have standard joins implemented, so it would be useful to see what happens in those two backends. For large (and even not very large) datasets marklogic joins are not very performant so to get a result in marklogic you'll probably need to use a small dataset.

**Comment by nicflores** [comment] 2017-07-14 22:30
Thanks @alissapajer for that info. I'm about to run the same query in Marklogic to see what happens there.

**Comment by alissapajer** [comment] 2017-07-14 22:32
Sounds good. Also when you paste further results feel free to omit the qscript. It will be similar for all backends, and the ticket will be easier to read through if we don't have those large trees.

**Comment by sellout** [comment] 2017-07-14 22:47
Ah, yeah – Couchbase and joins don’t really mix (yet). Marklogic is probably a good bet, though.

I see that the both joins are crosses. And that probably explains the Mongo error – as, in Mongo, a cross is handled by turning each collection into a single array, then `$unwinding` each of them. So you’re turning all of both collections into one document, and that’s probably what “value too large to reduce” is complaining about.

I would _like_ the QScript to look like
```scala
EquiJoin(
  Unreferenced(),
  ShiftedRead("/mongo/testdata/patients.data", ExcludeId)
  Reduce(
    Map(
      ShiftedRead("/mongo/testdata/zips", ExcludeId)
      ProjectField(Hole, "state")),
    List(Hole),
    Nil,                 // although this probably will be `List(Arbitrary(Hole))`
    ReduceIndex(0.left)) // and this will be `0.right`
  List((ProjectField(Hole, "state"), Hole)),
  Inner,
  LeftSide)
```
I wrote that from the original query, but my common workaround when users have a problem like this is to tell them to make the join explicit, like
```sql
select p.*
  from `/mongo/testdata/patients.data` as p
  join (select distinct state from `/mongo/testdata/zips`) z
  on p.state = z.state
```
which matches the QScript I’ve written. Note that for the explicit join approach to work that `distinct` needs to be added.

I feel like the conversion of `in` to `within()` is maybe getting in the way – that’s what triggers the `UnshiftArray` reduction. But I don’t know if that’s what’s causing the query failure – just that it’s making the QScript more complicated than it could be.

**Comment by nicflores** [comment] 2017-07-17 22:20
Finally got the query to work on marklogic. I had to significantly reduce the size of the patients and the zips file:
```
 [366] → cat zips | wc -l
      83
 [367] → cat patients.data | wc -l
     111
```

**Comment by alissapajer** [comment] 2017-07-20 00:21
@nicflores to confirm, is the query returning correct results on marklogic?

**Comment by nicflores** [comment] 2017-07-20 00:29
The ML query was successful, I didn't verify the result to make sure it was correct.

**Comment by nicflores** [comment] 2017-07-20 21:11
It is likely that some of QScript work that @wemrysi and @alissapajer are doing will resolve this issue. Specifically we are looking to remove the extra `EquiJoin` we are seeing in the `QScript` output.

**Comment by nicflores** [comment] 2017-07-20 21:13
Running the equivalent version of the query mentioned above by @sellout we get a different error:

```
💪 $ select p.* from `/mongo32/local/patients` as p join (select distinct state from `/mongo32/local/zips`) as z on p.state = z.state


Quasar error: Plan execution failed: MongoDB Error: Command failed with error 139: 'TypeError: value[0] is undefined :
@:5:49
@:5:1
@:4:1
' on server 192.168.99.101:27021. The full response is { "ok" : 0.0, "errmsg" : "TypeError: value[0] is undefined :\n@:5:49\n@:5:1\n@:4:1\n", "code" : 139 }, cause=Some(Command failed with error 139: 'TypeError: value[0] is undefined :
@:5:49
@:5:1
@:4:1
' on server 192.168.99.101:27021. The full response is { "ok" : 0.0, "errmsg" : "TypeError: value[0] is undefined :\n@:5:49\n@:5:1\n@:4:1\n", "code" : 139 })
```

**Comment by alissapajer** [comment] 2017-10-10 16:30
I ran the query
```sql
SELECT * FROM patients AS p where state in (SELECT state FROM zips)
```
against PR #2902 and it gives the error
```
Quasar error: Plan execution failed: MongoDB Error: Command failed with error 13070: 'value too large to reduce'
```

**Comment by djspiewak** [comment] 2017-10-30 21:59
So this will crash mimir as well.  It's just a really bad query because of how `IN` has to work.  I'm relatively certain the following constitutes a valid workaround:

```sql
SELECT * FROM patients AS p where state in (SELECT DISTINCT state FROM zips)
```

**Comment by djspiewak** [comment] 2017-11-26 02:08
@alissapajer Is this one rightfully skulled? Qsu doesn’t really fix this, because at the end of the day, the problem stems from the user asking us to page a very large dataset into memory. If this sort of thing is really really important, then we could hard code some behavior in the case that IN is applied to a subselect, but ultimately what the user is requesting here is just not evaluable in general.

**Comment by alissapajer** [comment] 2017-11-26 02:37
@djspiewak since the originally reported bug has been fixed, and we have a workaround to avoid paging the entire dataset into memory, I think we can unskull this.

Let's write a couple integration tests for
```sql
SELECT * FROM patients AS p where state in (SELECT state FROM extraSmallZips)
```
and
```sql
SELECT * FROM patients AS p where state in (SELECT DISTINCT state FROM zips)
```
and then close this issue.

**Comment by alissapajer** [comment] 2017-11-26 02:39
Actually, we do want both those above queries to work, so I'm going to add the skull back, knowing that this issue will be closed when we write those two tests. If those two tests don't pass for other reasons, then we'll open new issues for them.

**Comment by djspiewak** [comment] 2017-12-04 18:47
Both of these queries work now.  I'll create integration tests.

**Comment by alissapajer** [comment] 2017-12-04 22:00
@djspiewak last time I checked this, in the version without `distinct` we were getting multiple rows returned per `state`, which is incorrect. The integration tests you added don't check for this property. Can you see if this is still happening?

**Comment by alissapajer** [comment] 2017-12-04 22:04
Actually, because of the `order by` in the integration test, I think you are testing this property implicitly.

**Comment by djspiewak** [comment] 2017-12-04 22:04
@alissapajer Multiple rows per state is correct.  What we don't want is rows to get duplicated because of the join.  A quick check of `count(*)` with and without the distinct, things appear to be fine.

**Comment by djspiewak** [comment] 2017-12-04 22:05
Oh yeah, and I guess the `order by` does check that.  :-)

**Comment by alissapajer** [comment] 2017-12-04 22:07
@djspiewak I may have not understood the `in` operator correctly. Does it not treat the values that follow it as a set, thus implicitly `distinct`ing them?

**Comment by alissapajer** [comment] 2017-12-04 22:09
I think we are on the same page now, actually. There can be multiple rows per `state` returned, but we don't want them duplicated, as you said above.

**Closed** 2017-12-05 23:28 UTC
Labels: status: In review, type: Bug, ☠️
