### ISSUE TITLE
mongodb: order of fields in result does not match physical plan

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#598] opened 2015-02-05 18:29 UTC
As discussed in #584, MongoDB has a surprising behavior in the way fields get ordered in a $project op where some of the fields refer to fields that appear in the source collection.

In SlamData, you can mostly see this when the query is relatively trivial. For example, a query like `select _id as zip, city from zips` produces a physical plan with fields in the correct order, but results like `{ "city": "BOULDER", "zip": "80301" }`, because `city` is preserved from the source, and `zip` is added by the final $project (or at least, that's one way of describing the behavior).

Possible fixes:

1. Introduce some spurious renaming. This would obviously make the physical plan more complicated.
2. Keep information about the desired field order and restore it when reading from the result collection. This will require collection metadata, a post-2.0 thing.
3. MongoDB could fix it, if they agree it's a bug.

**Comment by mossprescott** [comment] 2015-02-05 18:29
*More details, from a comment on #584:*

If a final $project happens to include any fields which are projected directly from the source collection, *and not renamed*, then the order of those fields is not the order they are mentioned in the $project, but the order of the fields in the source. Any fields with "new" names always follow, in the order they appear. If all the fields are projected under different names, sanity resumes. Check this out:

```
💪 $ select a as a, b as b from "tmp.foo"
Query time: 0.0s
{ "a": 1, "b": 2 }
{ "b": 4, "a": 3 }

💪 $ select a as aa, b as bb from "tmp.foo"
Query time: 0.0s
{ "aa": 1, "bb": 2 }
{ "aa": 3, "bb": 4 }

💪 $ select 'x', a, b from "tmp.foo"
Query time: 0.0s
{ "a": 1, "b": 2, "0": "x" }
{ "b": 4, "a": 3, "0": "x" }
```

**Comment by mossprescott** [comment] 2015-02-06 19:39
In fixing #584, it became clear that this issue comes up more often than I previously thought, because the relevant "source" for the final $project op is the preceding shape-creating op. One common case is that a $group op creates some of the projections and some temporaries, and then the final project propagates the completed fields and adds the rest based on the temps.

For example:
```
💪 $ select avg(pop)/1000, count(*) from zips group by state
Mongo
db.zips.aggregate([
    { "$group" : { "__tmp0" : { "$avg" : "$pop"} , "1" : { "$sum" : { "$literal" : 1}} , "_id" : "$state"}},
    { "$project" : { "0" : { "$divide" : [ "$__tmp0" , { "$literal" : 1000}]} , "1" : "$1"}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.find()

Query time: 0.3s
{ "1" : 484 , "0" : 10.055148760330578}
```

**Comment by jdegoes** [comment] 2015-06-16 17:02
MongoDB has currently [closed this issue as *wontfix*](https://jira.mongodb.org/browse/SERVER-18074), but users have been more frequently complaining.

**Comment by jdegoes** [comment] 2015-06-16 17:05
Yay, issue opened as feature request. :smile:

**Comment by asya999** [comment] 2015-06-16 17:11
In general, field order in documents is not guaranteed, hence this is not a bug.  However, it's reasonable to want a specific field order, hence this is going to be considered as a possible enhancement.

**Comment by jdegoes** [comment] 2015-06-16 17:15
:+1: :fireworks: :wine_glass: 

We hope a lot of users vote for this enhancement. Actually, let me go bug some SlamData users about it... :wink:

**Closed** 2015-12-11 16:43 UTC
Labels: bug
