### ISSUE TITLE
CB: Enable remaining query integration tests

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1607] opened 2016-10-19 15:53 UTC
This is a bit of a catch all and will likely spawn new issues as additional tests are being enabled.

Test | Status
--- | ---
caseVariations.test | distinct/ordering bug (ordering lost on reduce step)
caseWithGroup.test | distinct/ordering bug
citiesByLargestZip.test | distinct/ordering bug
different-flattens.test | #1951 qscript provenance bug
flattenArrayLeftWithUnflattened.test | #2360 CB RuntimeException
flattenArrayWithUnflattened.test | #2360 CB RuntimeException
flattenGroupedObject.test | qscript bug - unnecessary join
groupByExpression.test | fixed pending merge of #2106 
groupByFlatten.test | qscript bug - unnecessary join
joins/3WayJoin.test | unimplemented EquiJoin
joins/constantOnLeft.test | unimplemented EquiJoin
joins/crossJoin.test | unimplemented EquiJoin
joins/crossJoinWithOneSidedConditions.test | unimplemented EquiJoin
joins/groupedJoin.test | unimplemented EquiJoin
joins/innerEquiJoin.test | unimplemented EquiJoin
joins/innerEquiJoinWithWildcard.test | unimplemented EquiJoin
joins/joinSubSelects.test | unimplemented EquiJoin
joins/joinWithComplexCondition.test | unimplemented EquiJoin
joins/joinWithMultipleConditions.test | unimplemented EquiJoin
joins/joinWithReversedCondition.test | unimplemented EquiJoin
joins/nonJsJoinCondition.test | unimplemented EquiJoin
joins/orderJoinByAlias.test | unimplemented EquiJoin
joins/sameFieldName.test | unimplemented EquiJoin
joins/symmetricNonJsJoinCondition.test | unimplemented EquiJoin
locationCount.test | qscript bug - unnecessary join
mongodb/distinctStar.test | NA
mongodb/fakeObjectId.test | NA
mongodb/fieldOrder.test | NA
mongodb/filterOnContains.test | NA
mongodb/projectIndexFromGroup.test | NA
mongodb/selectWildcardAndField.test | NA
mongodb/unshiftAggregation.test | NA
multistageFlatten.test | qscript bug - unnecessary join
multitypeFlatten.test | qscript bug - unnecessary join
null/nullTestExprsWithMissing.test | returning incorrect results
projectFieldWithFlatten.test | investigation required - likely CB bug
projectIndexFromGroup.test | fixed pending merge of #2106
projectIndexWithObjectFlatten.test | investigation required - likely CB bug
servlet.test | #465, #467
shortCities.test | distinct/ordering bug
skipCount.test | _Investigation required_ seems to be a faulty tmpName
statesByShortestFirstCity.test | unknown, likely just CI slowness
temporal/timestampsAndIntervals.test | #1601 Implement Interval QScript term
unifyFlattenedFields.test | investigation required - likely CB bug
unifyFlattenedFieldsWithMultipleUses.test | #2366 LogicalPlan bug
unifyFlattenedFieldsWithUnflattened.test | #2360 couchbase exception thrown
union.test | _Adjust impl_
unshiftAggregation.test | Group contents ordering differs and `SORT BY` is not yet available

**Comment by alissapajer** [comment] 2017-02-17 19:37
Updated as of ce9932a90bb13df3dd1382b68cb83c3f827b376f. Didn't verify the causes of many of the disabled tests, but overall the table should generally be correct.

**Comment by drostron** [comment] 2017-02-17 21:13
@alissapajer Thanks for updating the issue per latest fixes and test enablement.

**Comment by alissapajer** [comment] 2017-12-08 23:28
Closing, as these tests are all tracked by individual issues.

**Closed by alissapajer** 2017-12-08 23:28 UTC
Labels: epic: Connector: Couchbase Overhaul, status: On hold, status: Ongoing, topic: Couchbase
