### ISSUE TITLE
Broken code or broken test with MOVE

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1357] opened 2016-08-12 16:39 UTC
```
[info]   + [SD-1833] replace view
[error]   x MOVE view
[error]    '\/-(404 Mount point not found.)' is not \/- with value'200 OK' (ServiceSpec.scala:162)
```

**Comment by jdegoes** [comment] 2016-08-12 19:33
```
[info] /mount/fs should
[info]   + POST view (2 seconds, 983 ms)
[error]   ! PUT view (1 second, 472 ms)
[error]    java.net.BindException: Address already in use (Net.java:-2)
[error] sun.nio.ch.Net.bind0(Native Method)
[error] sun.nio.ch.Net.bind(Net.java:436)
[error] sun.nio.ch.Net.bind(Net.java:428)
[error] sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
[error] org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anonfun$bind$1.apply(NIO1SocketServerGroup.scala:63)
[error] org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anonfun$bind$1.apply(NIO1SocketServerGroup.scala:62)
[error] org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.bind(NIO1SocketServerGroup.scala:62)
[error] org.http4s.server.blaze.BlazeBuilder.org$http4s$server$blaze$BlazeBuilder$$$anonfun$2(BlazeServer.scala:180)
[error] org.http4s.server.blaze.BlazeBuilder$$Lambda$330/1967972333.apply(Unknown Source)
```

**Comment by nicflores** [comment] 2017-04-24 21:46
Is there a chance these errors happened in an old travis job that I can go back and inspect? Running the `ServiceSpec` locally all test pass. It may be difficult to try to reproduce these errors locally and maybe I should try this on travis. 

`ServiceSpec` does spin up its own server on port 8888, I can see the second error possibly stemming from a concurrency issues, but maybe that is something that's fixed now that the specs are ran sequentially.

**Comment by alissapajer** [comment] 2017-04-24 21:55
@nicflores so I haven't seen this particular failure for a few months, which isn't to say it's fixed, but I don't think we'll be able to pull up a failing travis build (especially since we would have restarted the build and overwritten the previous one in travis).

Since there is always a chance that something like this is fixed, it's probably not worth spending too much time trying to reproduce, unless you can reason through what might be the cause.

And eventually we should just close some of these unreproducible test issues if we haven't seen the failure for months. We can always reopen if we see the failure again.

**Comment by nicflores** [comment] 2017-04-24 22:52
Thanks for the feedback, @alissapajer. Maybe I'll just put this on the back burner just in case it creeps up again. If it doesn't then maybe we can all agree to just go ahead and close it.

**Comment by jedesah** [comment] 2017-04-24 23:37
Considering the date this was opened and [this](https://github.com/quasar-analytics/quasar/commit/eb0578a5638b9e10020f6f2d35a2db4cbcd802c5) commit by @rabbitonweb. I think it's likely that second error has been fixed. As for the first one, if we can't reproduce it easily, I say we close this till someone runs into again (if that happens).

**Closed** 2017-05-11 21:43 UTC
Labels: epic: Miscellaneous Quasar Issues, type: Bug
