### ISSUE TITLE
MongoDB: Timestamp values changes after Flattening

### ISSUE THREAD

**Issue by sriksrin** [quasar-analytics/quasar#1994] opened 2017-03-21 04:05 UTC
Hi,

 I created a sample document in MongoDB for knowing how flattening works. 

This is the document i created

 {
   "dvcid":"1_!",
    "ts":  ISODate("2017-01-01T00:00:00Z"),
    "temp": {
           "0": 20,
           "1": 30,
           "2": 24,
           "3": 23
        }
}

when, queried without flattening i.e. 
  SELECT dvcid,
ts,
temp
FROM `/test/test/test1`

the ts values shows the proper value. i.e whats there in the mongodb.

But, when queired with flattening 
  SELECT dvcid,
ts,
temp{*}
FROM `/test/test/test1`

the "ts" values are not what is stored in mongodb. The current time stamp/ system timestamp is considered and shown in the output.

Why is this happening? 
How to enforce "ts" values to show from mongodb and not take system time?

Regards,
Srikanth

**Comment by zeeiyerWork** [comment] 2017-03-22 00:29
Sounds like this is a correctness issue - and hence important to fix. Let's see if this behavior goes away with the new Mongo connector. !

**Comment by jsantos17** [comment] 2017-08-09 03:24
This is still happening with next-major:

I added a `ts` column to `smallZips.data` to try this.

Without flattening:  `SELECT loc[1], loc[2], ts  FROM 'mngo/test/smallZips'` yields

```
 0          | ts                    |
------------|-----------------------|
  42.070206 |  2017-01-05T00:00:00Z |
  42.377017 |  2017-01-05T00:00:00Z |
  42.409698 |  2017-01-05T00:00:00Z |
  42.275103 |  2017-01-05T00:00:00Z |
  42.182949 |  2017-01-05T00:00:00Z |
  42.116543 |  2017-01-05T00:00:00Z |
  42.279421 |  2017-01-05T00:00:00Z |
   42.38167 |  2017-01-05T00:00:00Z |
  42.162046 |  2017-01-05T00:00:00Z |
  42.176443 |  2017-01-05T00:00:00Z |
```

which includes the correct date stored in Mongo.

With flattening: `SELECT loc[*], ts  FROM '/mngo/test/smallZips'` yields

```
 loc         | ts                        |
-------------|---------------------------|
  -72.622739 |  2017-08-09T03:21:46.928Z |
   42.070206 |  2017-08-09T03:21:46.928Z |
   -72.51565 |  2017-08-09T03:21:46.929Z |
   42.377017 |  2017-08-09T03:21:46.929Z |
  -72.108354 |  2017-08-09T03:21:46.929Z |
   42.409698 |  2017-08-09T03:21:46.929Z |
  -72.410953 |  2017-08-09T03:21:46.930Z |
   42.275103 |  2017-08-09T03:21:46.930Z |
  -72.936114 |  2017-08-09T03:21:46.930Z |
   42.182949 |  2017-08-09T03:21:46.930Z |
```

which includes the current datetime :/

**Comment by jdegoes** [comment] 2017-08-09 14:30
![](https://media.giphy.com/media/3og0IHreZnBrBkJO7e/source.gif)

**Comment by jdegoes** [comment] 2017-08-09 14:30
😦

**Comment by jsantos17** [comment] 2017-08-17 20:06
Found the cause of this bug, it's in the `clone` function we use in Map-Reduce plans. So, 

```javascript
> clone(ISODate("2017-01-01"))
ISODate("2017-08-17T20:01:32.516Z")
```

will submit a PR with a fix soon.

**Comment by jsantos17** [comment] 2017-09-08 16:56
Verified as fixed in new Mongo

**Closed by jsantos17** 2017-09-08 16:56 UTC
Labels: epic: Connector: New Mongo - Initial Production Rollout, status: Fixed in New Mongo, status: In review, topic: MongoDB, type: Bug
