### ISSUE TITLE
Compile takes too much time

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2843] opened 2017-09-27 18:18 UTC
I have a view with following query 
```sql
CREATE FUNCTION ROUND1(:val) BEGIN FLOOR1(0.5 + :val) END; CREATE FUNCTION CEIL1(:val) BEGIN FLOOR1(1 + :val) END; CREATE FUNCTION FLOOR1(:val) BEGIN CASE WHEN (:val % 1) = 0 THEN :val WHEN :val < 0 THEN (:val - :val % 1) - 1 ELSE :val - :val % 1 END END; CREATE FUNCTION ROUND(:val, :n) BEGIN ROUND1(:val * 10.0 ^ :n) / 10.0 ^ :n END; CREATE FUNCTION CEIL(:val, :n) BEGIN CEIL1(:val * 10.0 ^ :n) / 10.0 ^ :n END; CREATE FUNCTION FLOOR(:val, :n) BEGIN FLOOR1(:val * 10.0 ^ :n) / 10.0 ^ :n END; SELECT FLOOR(measureOne, -1) AS abscissa, FLOOR(measureTwo, -1) AS ordinate, SUM(measureThree) AS measure, null AS series FROM `./out2b2fce20-81cd-4a67-9305-49613afbf7a9` GROUP BY FLOOR(measureOne, -1), FLOOR(measureTwo, -1) ORDER BY FLOOR(measureOne, -1) ASC, FLOOR(measureTwo, -1) ASC
```
`GET`tting from it (i.e. `GET@/data/fs/path/to/that/view`) takes ~987ms
But `GET@/compile/fs?q=THAT_QUERY` takes ~25s. 

quasar version 23.1.2 

Is this something that could be easily fixed, or we should switch off compile/inputs checks in frontend?

**Comment by jdegoes** [comment] 2017-09-27 19:56
That's NOT good. Definitely a bug that needs fixing.

**Comment by djspiewak** [comment] 2017-09-27 20:00
Might not necessarily be easy to fix, but clearly important.

**Comment by cryogenian** [comment] 2017-09-28 12:13
I'll comment `compile` pieces in SlamData untill this is fixed, because it dramatically changes user experience.

**Comment by beckyconning** [comment] 2017-09-29 14:53
Commenting out these pieces makes sharing inoperable in many situations.

https://github.com/slamdata/slamdata/pull/2283/files?diff=unified#r141848599

**Comment by zeeiyerWork** [comment] 2017-09-29 15:51
Yeah - seems like we need to bump the priority on this based on @garyb comment 
>> upgrade quasar-analytics/quasar#2843 to a blocker, since it seems like both options are bad currently:
>> - Keep it, and it's super slow
>> - Drop it, and sharing probably won't work

**Comment by rintcius** [comment] 2017-09-29 18:19
@cryogenian 
Looking at the query, I think some of these function definitions are not necessary anymore because sql^2 supports FLOOR, CEIL etc directly now. Does it compile faster if you use those instead?

**Comment by cryogenian** [comment] 2017-09-29 18:45
@rintcius Do you mean that Sql^2 supports positioning flooring|rounding|ceiling i.e. `FLOOR(123, 2) = 120`?

**Comment by djspiewak** [comment] 2017-09-29 18:45
No but in your query, you're not using the positional rounding.

**Comment by cryogenian** [comment] 2017-09-29 18:47
`ORDER BY FLOOR(measureOne, -1) ASC, FLOOR(measureTwo, -1) ASC`

**Comment by djspiewak** [comment] 2017-09-29 18:47
Oh I see. Rip…

**Comment by rintcius** [comment] 2017-09-29 18:53
@cryogenian  No, not the positional ones but e.g. the functions you called `FLOOR1`, `CEIL1`

**Comment by cryogenian** [comment] 2017-09-29 18:53
Okay, I'll try do this w/o defined funcs

**Comment by cryogenian** [comment] 2017-09-29 19:07
Okay, I can't have that bad performance as I had when I opened this issue. Now it's ~6s for defining both `FUNC1` and `FUNC`. It's something ~2s w/o `FUNC1`. W/o any functions it's ~0.4s. 

Please note, that I tested performance using mimir because I can't mount mongo in latest quasar (windows issue), and can't use builtin `FLOOR|ROUND|CEIL` in `23.x.x`. But in `23.x.x` w/o any funcs performance is ~0.4s on mongo too.

**Comment by alissapajer** [comment] 2017-09-29 19:27
I'll look into this ASAP.

**Comment by rintcius** [comment] 2017-09-29 19:35
@alissapajer still good to look into but seems less of a burning issue now, I think?

**Comment by alissapajer** [comment] 2017-09-29 19:40
@rintcius sounds good. When I finish my current work I'll touch base with folks to determine what the next most pressing issue is.

**Comment by jdegoes** [comment] 2017-09-29 19:40
This is "unacceptably" long but now it's mostly a matter of fighting the most raging fires, since there are so many other performance regressions that must be investigated.

Not sure we can ship 4.3 without this fixed though. /cc @zeeiyerWork

**Comment by djspiewak** [comment] 2017-09-29 19:42
I'm not sure I agree that a 400ms response time is unacceptably long for a compile that also has to round-trip to the server, perform several analyses, and actually generate a plan (for some connectors, not mimir obviously).  Obviously it could be a lot better.  And the multi-second madness is unequivocally unacceptable.

**Comment by jdegoes** [comment] 2017-09-29 19:47
To get 400ms, all the functions have to be deleted. And even 400ms is unacceptable long-term. We can live with it in the short-term, if necessary, but compilation for such a tiny query, including all the functions, should be nearly instantaneous. We shouldn't be slower than GCC on 100,000 lines of code.

We have a lot of work to do, in order to get where we need to be, but hopefully this pathological performance w/functions is something simple and we can fix without too much issue.

**Comment by wemrysi** [comment] 2017-09-29 19:56
I absolutely agree that there are lots of ways we can, and should, improve things, but to set expectations a bit, while this endpoint is "compiling" from a user point of view, compilation down to the physical plan involves a dialog with the underlying datastore itself, i.e. network traffic, to determine the final result. This isn't just a SQL-> QScript compilation.

**Comment by jdegoes** [comment] 2017-09-29 20:01
@wemrysi Sure, but interactions with a local database have latency on the order of milliseconds. You can fit a whole lot of those in 400ms. Profiling will determine the answer.

**Comment by djspiewak** [comment] 2017-09-29 20:04
@jdegoes Under ideal circumstances, yes.  Even a local database can have a significantly higher latency than you're assuming, depending on the question being asked, and there's no guarantee that the database is local.  No one is arguing that we're optimal in terms of performance on this endpoint, but setting your expectations based on GCC is a bit like asking why it takes so long to ride an A train from Brooklyn to Harlem when we can fly from New York to Chicago in 2 hours: the semantics are simply not analogous.

**Comment by jdegoes** [comment] 2017-09-29 20:05
@djspiewak Profiling will show whether those 400ms are primarily spent waiting on socket IO or spent in other things that we have more direct control over. I'm betting the latter.

**Comment by wemrysi** [comment] 2017-09-29 20:07
As an aside, if the compile endpoint is being utilized less for the compiled output and more for the physical paths involved in the query, we could look into separating the two, or at least providing a way to obtain the latter without incurring the cost of the former.

**Comment by garyb** [comment] 2017-09-29 20:50
That might be good to have, but this is also used to determine whether there is an error in the query. We can wait until pulling data from the view to get that error, but it means query errors in the front end won't appear until one step after the query was defined, which isn't entirely ideal!

**Comment by djspiewak** [comment] 2017-10-02 17:30
So digging into this a little further, I'm actually wondering if this isn't functions at all, but rather another manifestation of the `case` issue in qscript (which @alissapajer fixed quite recently).  Also, I'm relatively certain that it isn't just `compile` that's slow, but actually evaluation as well, it's just that the asynchronous nature of cached views hides it.

**Comment by djspiewak** [comment] 2017-10-02 18:07
Here's the fully-inlined query.  This has absolutely nothing to do with function resolution or compilation.  At least, not directly:

```sql
SELECT (CASE WHEN (measureOne * 10.0 ^ -1 % 1) = 0 THEN measureOne * 10.0 ^ -1 WHEN measureOne * 10.0 ^ -1 < 0 THEN (measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1) - 1 ELSE measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1 END) / 10.0 ^ -1 AS abscissa, (CASE WHEN (measureTwo * 10.0 ^ -1 % 1) = 0 THEN measureTwo * 10.0 ^ -1 WHEN measureTwo * 10.0 ^ -1 < 0 THEN (measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1) - 1 ELSE measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1 END) / 10.0 ^ -1 AS ordinate, SUM(measureThree) AS measure, null AS series FROM `./out2b2fce20-81cd-4a67-9305-49613afbf7a9` GROUP BY (CASE WHEN (measureOne * 10.0 ^ -1 % 1) = 0 THEN measureOne * 10.0 ^ -1 WHEN measureOne * 10.0 ^ -1 < 0 THEN (measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1) - 1 ELSE measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1 END) / 10.0 ^ -1, (CASE WHEN (measureTwo * 10.0 ^ -1 % 1) = 0 THEN measureTwo * 10.0 ^ -1 WHEN measureTwo * 10.0 ^ -1 < 0 THEN (measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1) - 1 ELSE measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1 END) / 10.0 ^ -1 ORDER BY (CASE WHEN (measureOne * 10.0 ^ -1 % 1) = 0 THEN measureOne * 10.0 ^ -1 WHEN measureOne * 10.0 ^ -1 < 0 THEN (measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1) - 1 ELSE measureOne * 10.0 ^ -1 - measureOne * 10.0 ^ -1 % 1 END) / 10.0 ^ -1 ASC, (CASE WHEN (measureTwo * 10.0 ^ -1 % 1) = 0 THEN measureTwo * 10.0 ^ -1 WHEN measureTwo * 10.0 ^ -1 < 0 THEN (measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1) - 1 ELSE measureTwo * 10.0 ^ -1 - measureTwo * 10.0 ^ -1 % 1 END) / 10.0 ^ -1 ASC

```

**Comment by cryogenian** [comment] 2017-10-30 11:45
I'm going to reopen this because following compile request takes ~3min 
```
http://localhost:8080/compile/fs/mimir/Untitled%20Workspace%208.slam/.tmp/?q=SELECT%20SUM(measureThree)%20AS%20measure%2C%20seriesTwo%20AS%20category%2C%20seriesThree%20AS%20stack%2C%20seriesFour%20AS%20parallel%20FROM%20%60./outa43912ea-8d6a-4be9-a66b-ef58237349e1%60%20GROUP%20BY%20seriesFour%2C%20seriesThree%2C%20seriesTwo%20ORDER%20BY%20seriesFour%20ASC%2C%20seriesThree%20ASC%2C%20seriesTwo%20ASC
```
Quasar 25.1.1, mimir connector, `./outa43912ea-8d6a-4be9-a66b-ef58237349e1` is just 
```
select * from `/mimir/flatViz
```

And `/mimir/flatViz` has only 256 records

**Comment by djspiewak** [comment] 2017-10-30 15:01
This will be fixed by the QSU changes. Even without looking at the generated qscript, I’m almost positive this is mergeSources failing.

@cryogenian Would you mind actually just opening a fresh issue and assigning me?  This compilation issue is broadly unrelated to the previous one.

**Comment by djspiewak** [comment] 2017-10-30 15:02
Oh as a sidebar, running compile on mimir does nothing in mimir other than return a static string (the juggler). So it’s a decent way of isolating whether the compilation issue is in mimir (as with the first iteration of this ticket) or in qscript (as with your latest report).

**Comment by garyb** [comment] 2017-10-30 17:38
@djspiewak surely it's not a totally constant response, as the reason we use `compile` is to discover the "inputs" (files/views/modules that data is being pulled from) for the query? If so, that might be something something that mimir needs to do that it currently does not :wink:

**Comment by djspiewak** [comment] 2017-10-30 20:02
All of that is computed by compilation. Mimir doesn’t return any of the data you receive from that endpoint.

**Comment by zeeiyerWork** [comment] 2017-11-01 20:24
Re-evaluate after QSU initial implementation.

**Comment by alissapajer** [comment] 2017-11-01 20:27
To summarize, there may be two separate issues here.

(1) slow compilation to qscript
(2) slow evaluation in mimir

The new `QSU` implementation will address (1). Once (1) is addressed, then we can evaluate if (2) is still an issue, given improved qscript.

**Comment by zeeiyerWork** [comment] 2017-11-21 21:44
Given above comment, skulling this. can be un-skulled if (1) is enough.

**Comment by djspiewak** [comment] 2017-11-23 22:41
The second compilation issue is now fixed in master.

@cryogenian Reminder on the original issue: you should use `round`, `round_scale`, `floor_scale` and `ceil_scale` from the standard library, rather than reemiting custom versions of these functions.

**Closed by djspiewak** 2017-11-23 22:41 UTC
Labels: epic: SQL²: Enhancements: Phase A, topic: SQL, type: Bug, ☠️
