### ISSUE TITLE
Module mounts fail to mount after restarting Quasar

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2370] opened 2017-06-22 16:47 UTC
I can create modules mounts, but if I restart Quasar, they all fail to mount with something like:
```
Warning: Failed to mount '/mongodb/tests/.trash/Untitled Workspace 4 1.slam/.tmp/out05fe877f-08cc-45de-8d4c-06051add59c1/' because 'Invalid mount config, '[module] CREATE FUNCTION card05fe877f08cc45de8d4c06051add59c1(:foo)
  BEGIN
    (select * from :foo)
  END', because: Unsupported filesystem type: module'.
```

**Comment by jedesah** [comment] 2017-06-22 16:48
This is a duplicate of #2282 I think

**Comment by natefaubion** [comment] 2017-06-27 18:30
In the latest master this is corrupting the metastore for me. All FS operations return a `500 ""` until I nuke the metastore.

**Comment by zeeiyerWork** [comment] 2017-07-11 19:02
@drostron -> could you test this scenario and reply if the metastore resilience added prevents something this catastrophic. If so, we can close this out since #2282 tracks the other issue.

**Comment by jedesah** [comment] 2017-12-03 11:28
Duplicate of #2282

**Closed by jedesah** 2017-12-03 11:28 UTC
Labels: epic: Metastore: Overhaul: Phase A, topic: Metastore, type: Bug
