### ISSUE TITLE
Incorrect single letter option for passing plugins folder

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2840] opened 2017-09-27 17:05 UTC
I just pulled down the most recent version of Quasar (24.0.15) and tried to use the `-P` flag to pass in the folder path to the plugins to load the new backend jar files.

I ran the following command:

```
java -jar ~/quasar/quasar-web-assembly-24.0.15.jar -c ./quasar-config.json -P ~/quasar/plugins/24.0.15/
```

which threw an error about an unknown option:

```
Error: Unknown option -P
Error: Unknown argument '/Users/douglasduncan/quasar/plugins/24.0.15/'
Try --help for more information.
Error: Failed to parse command line options. Specific error was printed to standard error output
```

Running help shows that the single letter option is `-p` which unfortunately is the same as given to `--port`.

```
java -jar ~/quasar/quasar-web-assembly-24.0.15.jar --help
quasar 24.0.15
Usage: quasar [initUpdateMetaStore] [options]

  -c, --config <value>     path to the config file to use
  -p, --plugins <value>    path to the plugins directory containing JAR files which will be loaded as backends
  -L, --content-location <value>
                           location where static content will be hosted on the Quasar server. Must begin with a /
  -C, --content-path <value>
                           path where static content lives on the file system
  -r, --content-path-relative
                           specifies that the content-path is relative to the install directory (not the current dir)
  -o, --open-client        opens a browser window to the client on startup
  -p, --port <value>       the port to run Quasar on
  --help                   prints this usage text

Command: initUpdateMetaStore
Initializes and updates the metastore.
```

**Comment by djspiewak** [comment] 2017-09-27 20:01
Duplicate of #2820

**Closed by djspiewak** 2017-09-27 20:01 UTC
