### ISSUE TITLE
different-flattens.test returning too many results

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1951] opened 2017-03-08 10:53 UTC
When running `different-flattens.test` spark-hdfs & spark-local gets the right result `{ "name": "Mary Jane", "age": 29, "title": "Dr" }` but with different cardinality. Test expects 4 values, spark gets 32.

Details in https://gist.github.com/rabbitonweb/1a4819d6e04fecfa630e7395dddca15e

**Comment by rabbitonweb** [comment] 2017-03-08 11:08
Same issue seem to be with `multitypeFlatten.test` Also right set of results but duplicated multiple times

**Comment by jdegoes** [comment] 2017-03-08 15:59
Holy batman, that's one complex QScript graph!

**Comment by alissapajer** [comment] 2017-03-08 16:42
This is likely the same issue as #1929 - an issue with provenance in `QScript`.

**Comment by zeeiyerWork** [comment] 2017-03-20 21:05
@alissapajer - assigning this to you, since you seem knowledgeable about this. If not appropriate please reassign. We do need to fix this in 4.2 (John confirmed), since this is about correctness. We also have a couple of people from the field reporting issues with the Spark connector.

**Comment by sellout** [comment] 2017-06-08 22:23
Duplicate of #1929.

**Closed by sellout** 2017-06-08 22:23 UTC
Labels: epic: QScript Improvements: Phase-A, status: In progress, topic: QScript, type: Bug
