### ISSUE TITLE
invalid DB name generated

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#852] opened 2015-07-30 17:32 UTC
We have a test in `CollectionSpec` that fails intermittently:
```
[info] ! never emit an invalid db name
[error]    RuntimeException: : A counter-example is './ ދ*./⾘ 跋/巁羜࿎侜$
[error] /': java.lang.RuntimeException: failed to parse ‘巁羜࿎侜$
[error] /’: string matching regex `\z' expected but `
[error] ' found
```
it looks like it’s caused by a newline in a collection name (although we should be handling newlines, and newlines should be tested in _every_ run, so maybe it’s `\r` or something else).

**Comment by mossprescott** [comment] 2015-07-30 17:45
When I tried to look at this earlier, it seemed like some kind of encoding issue where there was a character that *seemed* to be a newline, because it wasn't decoded properly, maybe. It's pretty hard to tell, since this only happens in Travis every once in a while. Maybe there's a way to generate only single-byte strings? Do we need to support all of Unicode?

**Comment by sellout** [comment] 2015-07-30 18:43
scalacheck _should_ spit out a seed every time a test fails, and there should be some way to pass that seed to test-only, so we can replicate that one test. Telling us the input that failed is helpful, but figuring out how to get that seed would be better.

**Comment by mossprescott** [comment] 2015-07-30 20:15
Partially addressed by https://github.com/rickynils/scalacheck/pull/171. See http://stackoverflow.com/questions/21508201/reproducing-a-scalacheck-test-run?rq=1 and https://stackoverflow.com/questions/12639454/make-scalacheck-tests-deterministic. Seems like it would probably be possible to cobble something together at this point, but I agree it *should* just happen.

**Closed** 2015-12-11 16:43 UTC
