### ISSUE TITLE
Filter Card with single phrase errors with OOM after ~1 hour

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2935] opened 2017-10-14 23:19 UTC
SlamData interface: 4.3.0 QA Preview 4
Quasar: 25.0.7

This is the filter being passed into the card (line breaks added for readability):

```
(
((SEARCH(age, "^.*Austin.*$", true)) OR
((SEARCH(city, "^.*Austin.*$", true))) OR
((SEARCH(*.codes[*].code, "^.*Austin.*$", true))) OR
((SEARCH(*.codes[*].`desc`, "^.*Austin.*$", true))) OR
((SEARCH(county, "^.*Austin.*$", true))) OR
((SEARCH(first_name, "^.*Austin.*$", true))) OR
((SEARCH(gender, "^.*Austin.*$", true))) OR
((SEARCH(height, "^.*Austin.*$", true))) OR
((SEARCH(last_name, "^.*Austin.*$", true))) OR
((SEARCH(last_visit, "^.*Austin.*$", true))) OR
((SEARCH(*.loc[*], "^.*Austin.*$", true))) OR
…(*.previous_addresses[*].latitude, "^.*Austin.*$", true))) OR
((SEARCH(*.previous_addresses[*].longitude, "^.*Austin.*$", true))) OR
((SEARCH(*.previous_addresses[*].state, "^.*Austin.*$", true))) OR
((SEARCH(*.previous_addresses[*].zip_code, "^.*Austin.*$", true))) OR
((SEARCH(*.previous_visits[*], "^.*Austin.*$", true))) OR
((SEARCH(state, "^.*Austin.*$", true))) OR ((SEARCH(street_address, "^.*Austin.*$", true))) OR
((SEARCH(weight, "^.*Austin.*$", true))) OR
((SEARCH(zip_code, "^.*Austin.*$", true)))))
```

The stack trace generated (thanks to @djspiewak for showing how to get this) is attached in the following file. The trace is 947 lines long, so I didn't copy/paste in the issue.

[stacktrace.txt](https://github.com/quasar-analytics/quasar/files/1385069/stacktrace.txt)

Steps to reproduce:

1. Create a new workspace and add an **Open** card.
2. Navigate to the **patients** file.
3. Advance and add a search card.
4. In the search enter **Austin**.
5. Advance and add a **Preview Table** card

This will start the process to search for the

**Comment by jdegoes** [comment] 2017-10-15 15:17
@dugdun For comparison, do you know how fast this same query runs in MongoDB?

**Comment by zeeiyerWork** [comment] 2017-10-15 16:11
Old-Mongo (demo server): On the UI it seems to return instantaneously so guess 1s or thereabouts.
Old-Mongo (local machine): similar. 
New-Mongo: Haven't tested (given some issues with my local install).
@djspiewak - could you please take a look and comment on potential LOE.

**Comment by djspiewak** [comment] 2017-10-15 16:34
This is almost certainly a qscript compilation issue. I can’t comment about LOE because I know comparatively little about that code. Old Mongo almost certainly special cases some things in here. New Mongo, which is what John was asking about, would confirm (or falsify) the qscript issue.

**Comment by dugdun** [comment] 2017-10-15 20:18
New MongoDB is similar to Mimir in processing. I had always cancelled out of the processing while running this in Mimir after about 20 minutes or so. I just now let this same process run on new Mongo and after 55 minutes it returned a server 500 error. The logs show it failed with an out of memory error causing the Quasar process to terminate.

This leads me to believe, as Daniel stated above, that it's a qscript issue. Let me know if there's any other information I can provide.

**Comment by dugdun** [comment] 2017-10-15 23:10
Mimir also failed after just over an hour with an out of memory error. Changed the title to reflect the issue.

**Comment by zeeiyerWork** [comment] 2017-10-16 01:27
This is a pretty simple invocation of the Search Card (a single word searched against all columns). Since it is basic functionality, it is pretty high priority imho. Hence I have added it to the October timeline and we should attempt to fix it if possible for the 5.0 release. @dugdun do you have the Qscript generated available - if so, please attach.
Fyi @alissapajer , @wemrysi

**Comment by alissapajer** [comment] 2017-10-16 15:08
@dugdun I can generate the qscript, so you don't need to attach it. The SQL^2 query is enough information at this point.

**Comment by wemrysi** [comment] 2017-10-17 16:54
I can confirm compile performance for this query is abysmal, it _did_ compile, but took 22min 12sec to do so 😞. Am looking into the cause.

There is also an issue with how we pull guards up through expressions causing the query to incorrectly return no results if any of the fields involved fails the `Str` guard introduced by the application of `search`, this was an easy fix and a PR will be incoming shortly. This issue affects all searches like this (all disjunctions involving guards, really), not just large ones.

Also, due to MRA semantics, in addition to (currently) poor performance, queries like this one with many flattens in the predicate will yield a result set with many duplicates, which may not be what the user of the search card expects.

**Comment by wemrysi** [comment] 2017-10-18 16:41
For reference, here are the [timings and QScript produced](https://gist.github.com/wemrysi/d4d1109fb0fd07740303ed6089e5b68c) for progressively more of the search query.

**Comment by djspiewak** [comment] 2017-11-15 20:21
Here's an example of some qscript for this query *form*, with both the current model (using joins) and the version that we will have after #3092: https://gist.github.com/262a5fa0e56d69746dede59320b263f6

**Comment by djspiewak** [comment] 2017-12-06 19:14
I'm actually just going to close this one now.  @edmundnoble's work is to make the plans more efficient for better evaluation, but it evaluates correctly *now* (under QSU) and compiles in a fraction of a second, which is what the OP was originally about.

**Closed by djspiewak** 2017-12-06 19:14 UTC
Labels: epic: Establish QSU, status: In progress, topic: QScript, type: Bug, ☠️
