### ISSUE TITLE
SQL'2 queries fail on Marklogic

### ISSUE THREAD

**Issue by Cmdv** [quasar-analytics/quasar#2348] opened 2017-06-19 14:17 UTC
### Description

Running bellow query fails, it works fine on MongoDB

### Reproduction guide
```
SELECT measureOne, measureTwo from `/test-mount/testDb/flatViz.json`
```

### Results
```
{
  "error": {
    "status": "No files to read from.",
    "detail": {
      "message": "No paths provided to read from.",
      "dirs": []
    }
  }
}
```

**Comment by Cmdv** [comment] 2017-06-19 14:19
This could also be seen as related to #2341

**Comment by zeeiyerWork** [comment] 2017-06-19 16:52
@wemrysi , @jsantos17 -> Please take a look. Wonder if this is a setup issue where no directory level indices were created on the Marklogic side.

**Comment by jsantos17** [comment] 2017-06-19 16:53
@Cmdv can you provide a link to the dataset you're using for the query?

**Comment by jsantos17** [comment] 2017-06-20 00:46
I tried to reproduce this bug, but I couldn't do it. Both with a JSON mount and an XML mount. I used [this file](https://github.com/slamdata/slamdata/blob/ef062fef0bcf512fb85aed81778fafc27305bd1e/test/dump/demo/flatViz.bson) which I converted to JSON using `bsondump` and then loaded it into Marklogic.

The error message is unfortunate and appears when you refer to a file that doesn't exist, so it might be worth checking for typos too.

@zeeiyerWork we don't have a requirement on directories anymore after #2273 so I don't think it's related. But just in case I tried with URI lexicon enabled and disabled to trigger the two codepaths we use for filesystem operations. Still no luck reproducing this issue.

**Comment by zeeiyerWork** [comment] 2017-06-20 00:48
Thanks.
@cmdv -> can you get with @jsantos17 or can we go ahead and close this as non-reproducible?

**Comment by Cmdv** [comment] 2017-06-20 09:20
@jsantos17 sorry I might have an issue with how I reproduction of this bug, my tests keep fluctuating from working then not working!! I do have a concrete example of a similar `No paths provided to read from.` which I will update once it is concrete 😄

**Comment by jsantos17** [comment] 2017-06-20 14:47
@Cmdv ping me when you get it. Happy to take another look :D

**Comment by jsantos17** [comment] 2017-06-22 15:09
@zeeiyerWork after talk with @Cmdv we agreed on closing this as not a bug.

**Closed by jsantos17** 2017-06-22 15:09 UTC
Labels: epic: Connector: Marklogic Overhaul, topic: MarkLogic, type: Bug
