### ISSUE TITLE
couchbase IT failure

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3235] opened 2017-12-05 16:30 UTC
Seen on Travis:

```
[error] ! geo_markers_step1 [./demo/geo_markers_step1.test] (503 ms)
[error]  java.lang.RuntimeException: Failed loading test data './demo/patients.data': null (QueryRegressionTest.scala:297)
[error] quasar.regression.QueryRegressionTest$$anonfun$loadTestData$1.applyOrElse(QueryRegressionTest.scala:297)
[error] quasar.regression.QueryRegressionTest$$anonfun$loadTestData$1.applyOrElse(QueryRegressionTest.scala:294)
[error] quasar.contrib.scalaz.concurrent.package$.quasar$contrib$scalaz$concurrent$package$$$anonfun$2(package.scala:29)
[error] com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:475)
[error] com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:456)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
[error] rx.observers.Subscribers$5.onNext(Subscribers.java:235)
[error] rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[error] rx.Subscriber.setProducer(Subscriber.java:211)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
[error] rx.Subscriber.setProducer(Subscriber.java:205)
[error] rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:364)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:69)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:382)
[error] rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[error] rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
[error] rx.observers.Subscribers$5.onNext(Subscribers.java:235)
[error] rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[error] rx.Subscriber.setProducer(Subscriber.java:211)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
[error] rx.Subscriber.setProducer(Subscriber.java:205)
[error] rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:364)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:69)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:382)
[error] rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[error] CAUSED BY
[error]  com.couchbase.client.java.error.TemporaryFailureException: null (CouchbaseAsyncBucket.java:475)
[error] com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:475)
[error] com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:456)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
[error] rx.observers.Subscribers$5.onNext(Subscribers.java:235)
[error] rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[error] rx.Subscriber.setProducer(Subscriber.java:211)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
[error] rx.Subscriber.setProducer(Subscriber.java:205)
[error] rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:364)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:69)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:382)
[error] rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[error] rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
[error] rx.observers.Subscribers$5.onNext(Subscribers.java:235)
[error] rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[error] rx.Subscriber.setProducer(Subscriber.java:211)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
[error] rx.Subscriber.setProducer(Subscriber.java:205)
[error] rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:364)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:69)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:382)
[error] rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[error] CAUSED BY
[error]  rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.couchbase.client.core.message.kv.InsertResponse.class (OnErrorThrowable.java:109)
[error] rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
[error] rx.observers.Subscribers$5.onNext(Subscribers.java:235)
[error] rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
[error] rx.Subscriber.setProducer(Subscriber.java:211)
[error] rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
[error] rx.Subscriber.setProducer(Subscriber.java:205)
[error] rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:364)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:69)
[error] com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:382)
[error] rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[info] StreamingQueryRegressionSpec
```

**Comment by alissapajer** [comment] 2017-12-05 18:24
Closing as this is a duplicate of #2329.

**Closed by alissapajer** 2017-12-05 18:24 UTC

**Comment by rintcius** [comment] 2017-12-06 08:04
Ah ok, I assumed that one was closed already (i.e. that it got closed once that test was marked `skip`), but better to keep it open until root cause is solved
