### ISSUE TITLE
travis-ci error in types.scala

### ISSUE THREAD

**Issue by nicflores** [quasar-analytics/quasar#3308] opened 2017-12-14 00:09 UTC
Bumped into this during one of my builds, reporting it here so we don't forget about it.

```
[error] x have order-independent equality for arbitrary types (82 ms)
[error]  Falsified after 54 passed tests.
[error]  > ARG_0: Const(Obj(Map($date -> Str(Jan 1))))
[error]  > ARG_1: Coproduct(Const(NA),Const(Obj(Map($date -> Str(Jan 1)))))
[error]  > constant value NA, or constant value Obj(Map($date -> Str(Jan 1))) !== constant value Obj(Map($date -> Str(Jan 1))) (QuasarSpecification.scala:52)
[error] quasar.QuasarSpecification$Specs2ScalazOps.must_$eq(QuasarSpecification.scala:52)
[error] quasar.TypesSpec.quasar$TypesSpec$$$anonfun$272(types.scala:388)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
[error] org.scalacheck.Prop$.secure(Prop.scala:456)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:712)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:749)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:706)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:291)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:713)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:749)
[error] org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:706)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
[error] org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:291)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[error] org.scalacheck.Test$.org$scalacheck$Test$$workerFun$1(Test.scala:294)
[error] org.scalacheck.Test$$anonfun$3.apply(Test.scala:323)
[error] org.scalacheck.Test$$anonfun$3.apply(Test.scala:323)
[error] org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[error] org.scalacheck.Test$.check(Test.scala:323)
[error] quasar.Qspec.check(QuasarSpecification.scala:31)
```

**Comment by drostron** [comment] 2017-12-14 00:57
Looks like a duplicate of #2194 and also reported by #2601

**Comment by zeeiyerWork** [comment] 2017-12-15 19:10
closing this since its a dupe.

**Closed by zeeiyerWork** 2017-12-15 19:10 UTC
Labels: status: Duplicate, type: Build
