### ISSUE TITLE
Quasar query fails when encountering value of NaN in MongoDB

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2221] opened 2017-05-18 21:17 UTC
SlamData 4.2.0
Quasar 16.1.5
MongoDB 3.x

Running into this issue with a commercial customer.

Given a dataset similar to the following:
```
{
	"_id" : "abc123",
	"testValue" : NaN
}
```
Any query referencing the collection will fail, unless the field containing `NaN` is excluded.

Query results in this error:
```
💪 $ select * from c2
💪 $ Exception in thread "AeshProcess: 5" java.lang.RuntimeException
	at quasar.effect.Failure$.quasar$effect$Failure$$$anonfun$16(Failure.scala:125)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:105)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:103)
	at scalaz.NaturalTransformation$$anon$2.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:57)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformation$$anon$2.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.Free.foldMap(Free.scala:217)
	at scalaz.Free.foldMap(Free.scala:219)
	at scalaz.Free$$anonfun$foldMap$2.apply(Free.scala:219)
	at scalaz.EitherT$$anonfun$flatMap$1$$anonfun$apply$4.apply(EitherT.scala:93)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.Free$$anonfun$step$1.apply(Free.scala:200)
	at scalaz.Free$$anonfun$step$1.apply(Free.scala:200)
	at scalaz.Free.step(Free.scala:202)
	at scalaz.Free.foldMap(Free.scala:215)
	at scalaz.Free$$anonfun$foldMap$2.apply(Free.scala:219)
	at scalaz.Kleisli$$anonfun$flatMap$1$$anonfun$apply$1.apply(Kleisli.scala:51)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:118)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
	at scalaz.concurrent.Future.unsafePerformSync(Future.scala:184)
	at scalaz.concurrent.Task.unsafePerformSync(Task.scala:99)
	at quasar.repl.Main$$anon$1.execute(Main.scala:81)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sellout** [comment] 2017-05-18 21:20
Duplicate of #1458.

**Closed by sellout** 2017-05-18 21:20 UTC
