### ISSUE TITLE
Query with multiple JOINs produces a result too large from MongoDB

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2434] opened 2017-07-06 00:27 UTC
Submitting issue at @sellout's request to get some assistance on a customer issue.

This is on SlamData 4.2.2, MongoDB 3.2 (possibly 3.4). All fields involved in the `JOIN`s are indexed, all collections are in the same database, no collections are sharded and these are equality matches. All of which are required by MongoDB to leverage `$lookup` instead of mapreduce to my knowledge. Yet we still see several mapreduce calls which I'm suspecting is the reason for such a large result set.

```
SELECT transactions.`_id` AS `TxID`
  FROM 
  `/mydb/clientdetails` as clientdetails
  INNER JOIN
    `/mydb/transactions` as transactions
    ON transactions.clientID = clientdetails.clientID
  INNER JOIN `/mydb/view_employeepositions`  as view_employeepositions
    ON view_employeepositions.clientID = transactions.clientID
```
Note that we are using a SQL² view in the final `JOIN`.  The view itself should also meet all requirements of MongoDB to leverage `$lookup`. I'll verify that though.

Customer states that the `hideFromKpi` *might* be boolean rather than string, if that is the case, is that the primary cause? Customer has been unable to re-test yet.

This query results in the following MongoDB requests:

```
db.clientdetails.aggregate(
  [
    { "$match": { "clientID": { "$exists": true } } },
    { "$project": { "left": "$$ROOT" } },
    {
      "$lookup": {
        "from": "transactions",
        "localField": "left.clientID",
        "foreignField": "clientID",
        "as": "right"
      }
    },
    { "$unwind": "$right" },
    {
      "$group": { "__tmp19": { "$push": "$$ROOT" }, "_id": { "0": "$right.clientID" } }
    },
    {
      "$project": {
        "_id": true,
        "value": { "left": "$__tmp19", "right": { "$literal": [] }, "_id": "$_id" }
      }
    },
    { "$out": "tmp.gen_484abbcc_0" }],
  { "allowDiskUse": true });
db.employeepositions.aggregate(
  [
    { "$match": { "locPosID": { "$exists": true } } },
    { "$project": { "left": "$$ROOT" } },
    {
      "$lookup": {
        "from": "locationpositions",
        "localField": "left.locPosID",
        "foreignField": "_id",
        "as": "right"
      }
    },
    { "$unwind": "$right" },
    {
      "$group": { "__tmp0": { "$push": "$$ROOT" }, "_id": { "0": "$right.locID" } }
    },
    {
      "$project": {
        "_id": true,
        "value": { "left": "$__tmp0", "right": { "$literal": [] }, "_id": "$_id" }
      }
    },
    { "$out": "tmp.gen_484abbcc_4" }],
  { "allowDiskUse": true });
db.locations.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) { return [{ "0": value._id }, { "left": [], "right": [value] }] })(
        this._id,
        this))
  },
  function (key, values) {
    var result = { "left": [], "right": [] };
    values.forEach(
      function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right)
      });
    return result
  },
  {
    "out": { "reduce": "tmp.gen_484abbcc_4", "db": "mydb", "nonAtomic": true },
    "query": { "hideFromKpi": { "$ne": "true" } }
  });
db.tmp.gen_484abbcc_4.aggregate(
  [
    {
      "$match": {
        "value.left": { "$not": { "$size": NumberInt("0") } },
        "value.right": { "$not": { "$size": NumberInt("0") } }
      }
    },
    { "$unwind": "$value.left" },
    { "$unwind": "$value.right" },
    { "$project": { "value": true, "_id": false } },
    { "$out": "tmp.gen_484abbcc_3" }],
  { "allowDiskUse": true });
db.tmp.gen_484abbcc_3.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) {
        return (function (key, value) {
          return [
            key,
            {
              "clientID": ((isObject(value.left) && (! Array.isArray(value.left))) && (isObject(value.left.left) && (! Array.isArray(value.left.left)))) ? value.left.left.clientID : undefined,
              "employeepositions_ID": ((isObject(value.left) && (! Array.isArray(value.left))) && (isObject(value.left.left) && (! Array.isArray(value.left.left)))) ? value.left.left._id : undefined,
              "currency": ((isObject(value.left) && (! Array.isArray(value.left))) && (isObject(value.left.left) && (! Array.isArray(value.left.left)))) ? value.left.left.currency : undefined,
              "locationpositions_name": ((isObject(value.left) && (! Array.isArray(value.left))) && (isObject(value.left.right) && (! Array.isArray(value.left.right)))) ? value.left.right.name : undefined,
              "locations_name": (isObject(value.right) && (! Array.isArray(value.right))) ? value.right.name : undefined
            }]
        }).apply(
          null,
          (function (key, value) { return [key, value.value] })(key, value))
      })(
        this._id,
        this))
  },
  function (key, values) { return values[0] },
  { "out": { "replace": "tmp.gen_484abbcc_2", "db": "mydb" } });
db.tmp.gen_484abbcc_2.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) {
        return (function (key, value) { return [{ "0": value.clientID }, { "left": [], "right": [value] }] }).apply(
          null,
          (function (key, value) { return [key, value.value] })(key, value))
      })(
        this._id,
        this))
  },
  function (key, values) {
    var result = { "left": [], "right": [] };
    values.forEach(
      function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right)
      });
    return result
  },
  {
    "out": { "reduce": "tmp.gen_484abbcc_0", "db": "mydb", "nonAtomic": true }
  });
db.tmp.gen_484abbcc_4.drop();
db.tmp.gen_484abbcc_2.drop();
db.tmp.gen_484abbcc_3.drop();
db.tmp.gen_484abbcc_0.aggregate(
  [
    {
      "$match": {
        "value.left": { "$not": { "$size": NumberInt("0") } },
        "value.right": { "$not": { "$size": NumberInt("0") } }
      }
    },
    { "$unwind": "$value.left" },
    { "$unwind": "$value.right" },
    { "$limit": NumberLong("11") },
    { "$project": { "TxID": "$value.left.right._id" } },
    { "$project": { "TxID": true, "_id": false } }],
  { "allowDiskUse": true });


Quasar error: Plan execution failed: MongoDB Error: Command failed with error 13548: 'BufBuilder attempted to grow() to 134217728 bytes, past the 64MB limit.' on server myserver:27017. The full response is { "ok" : 0.0, "errmsg" : "BufBuilder attempted to grow() to 134217728 bytes, past the 64MB limit.", "code" : 13548 }, cause=Some(Command failed with error 13548: 'BufBuilder attempted to grow() to 134217728 bytes, past the 64MB limit.' on myserver:27017. The full response is { "ok" : 0.0, "errmsg" : "BufBuilder attempted to grow() to 134217728 bytes, past the 64MB limit.", "code" : 13548 })
```

**Comment by rintcius** [comment] 2017-07-06 12:16
It looks like this particular view is causing the mapReduce. At least I tried a similarly structured query with a simple view underneath and that query runs with a single `aggregate`. Also the fact that it does `db.locations.mapReduce` (and assuming that `locations` is part of the view) makes me think that this view is the cause.

**Comment by damonLL** [comment] 2017-07-06 16:23
Thanks @rintcius! I think that makes sense... 

My assumption is: since a view is a dynamic query, we take those results and merge them with the other query. This configuration probably does not meet MongoDB's requirement of using $lookup.

But if you run a query and joined the results of a view with a query, I would have expected that to produce at least one mapreduce in there as well then. Doesn't that make sense?

**Comment by rintcius** [comment] 2017-07-10 13:36
I used a similarly structured query, but the underlying view is (probably) quite different. I used a very simple view, which didn't give rise for any `mapReduce`. I can imagine that running a simple select on your view would already give rise to a `mapReduce`. 

Let me know if I there's more for me to analyze - if that's the case, can you then give  me the details of the underlying view?

**Comment by sellout** [comment] 2017-07-10 14:13
@rintcius That sounds like a good analysis. It makes me think we should explicitly include the SQL for “non-native” views[†] in the error and/or explain.

@damonLL
> since a view is a dynamic query, we take those results and merge them with the other query

we actually merge the two queries directly, then run them as one, so
```sql
select * from cities order by city limit 10
```
where `cities` is a view like
```sql
select distinct city as city from zips
```
becomes a query like
```sql
select * from (select distinct city as city from zips) as cities order by city limit 10
```
which is optimized to
```sql
select distinct city as city from zips order by city limit 10
```

----
[†]: We _only_ have non-native views currently, but we should eventually take advantage of views in stores that support them, which should generally be much more efficient and not be visible in the QScript, so those don’t need to be called out so explictly in the explain.

**Comment by rintcius** [comment] 2017-07-20 08:52
@damonLL I'm closing, assuming the issue has been addressed, but of course feel free to reopen if you need more info.

**Closed by rintcius** 2017-07-20 08:52 UTC
Labels: epic: Connector: New Mongo - Initial Production Rollout, status: In progress
