### ISSUE TITLE
invoke endpoint doesn't work

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2947] opened 2017-10-17 17:04 UTC
version 25.0.16 mongo connector

I create module mount with following request
```json
{"module":"CREATE FUNCTION card993fa23532204ba18cad7aa9bdb74293(:chart, :filter) BEGIN CASE WHEN :chart = \"hbar\" THEN SELECT * FROM `./../out362707c2-8700-476b-8147-37245bc9a5d4hbar` AS res WHERE :filter END END"}
```

This request returns `{count: 16}`
```
http://localhost:8080/query/fs/test-mount/testDb/Untitled%20Workspace%201.slam/?q=IMPORT%20%60./.tmp/out993fa235-3220-4ba1-8cad-7aa9bdb74293/%60%3B%20tmp__0%20:=%20card993fa23532204ba18cad7aa9bdb74293(:chart%2C%20:filter)%3B%20SELECT%20COUNT(*)%20AS%20count%20FROM%20(tmp__0)%20AS%20tmp__1&var.chart=%22hbar%22&var.filter=TO_STRING(res.category)%20IN%20(%22one-four%22%2C%20%22one-two%22%2C%20%22one-one%22)
```

But this one returns 400 with `{ "error": { "status": "No files to read from.", "detail": { "message": "No paths provided to read from.", "dirs": [] } } }` 
```
http://localhost:8080/invoke/fs/test-mount/testDb/Untitled%20Workspace%201.slam/.tmp/out993fa235-3220-4ba1-8cad-7aa9bdb74293/card993fa23532204ba18cad7aa9bdb74293?chart=%22hbar%22&filter=TO_STRING(res.category)%20IN%20(%22one-four%22%2C%20%22one-two%22%2C%20%22one-one%22)&offset=0&limit=10
```

Am I doing anything wrong?

**Comment by cryogenian** [comment] 2017-10-17 17:11
Oh, yeah, I forgot to mention that this breaks consumer mode and visualization drilldown

**Comment by alissapajer** [comment] 2017-10-18 15:51
@cryogenian thanks for the report. 

This is preventing certain queries from working in the frontend so we will prioritize accordingly.

**Comment by zeeiyerWork** [comment] 2017-10-18 20:12
@jedsah - on first blush seems related to modules/REST endpoints. So please take a look. Higher priority than other feature work, since it is blocking additional QA and frontend work.

**Comment by jedesah** [comment] 2017-10-18 21:42
I'm looking into reproducing this.

@alissapajer Do you have any idea what it means when planning returns a `NoFilesFound` planner error? In particular, it looks like [this code](https://github.com/quasar-analytics/quasar/blob/master/connector/src/main/scala/quasar/qscript/DiscoverPath.scala#L209) is being hit. I'll probably figure it out if I can reproduce but it might help to have an idea what that means.

My guess is something around there being no files referenced in the plan which would lead me to believe that the `CASE WHEN :chart = "hbar"` expression might not be behaving as expected.

The `SQL` produced by the `invoke` endpoint might be flawed in some way. I'll know once/if I can reproduce.

**Comment by alissapajer** [comment] 2017-10-18 22:55
@jedesah the `NoFilesFound` case is hit when there are no static paths found in the qscript. Valid SQL^2 shouldn't ever hit this case, unless there is some bug in the qscript compiler. I'd be curious to see the SQL^2 query that is being run. It's also interesting that the query makes it as far as qscript compilation before erroring.

**Comment by garyb** [comment] 2017-10-19 20:34
Here's some CURLs for a failing case:

``` shell
curl 'http://localhost/mount/fs/mongo/test/Workspace.slam/.tmp/out76e34680-50ab-4547-bb10-44a913007dce' -X PUT -H 'Content-Type: text/plain;charset=UTF-8' --data-binary '{"view":{"connectionUri":"sql2:?q=CREATE%20FUNCTION%20ROUND2(:val%2C%20:n)%20BEGIN%20ROUND(:val%20*%2010.0%20%5E%20:n)%20/%2010.0%20%5E%20:n%20END%3B%20CREATE%20FUNCTION%20CEIL2(:val%2C%20:n)%20BEGIN%20CEIL(:val%20*%2010.0%20%5E%20:n)%20/%2010.0%20%5E%20:n%20END%3B%20CREATE%20FUNCTION%20FLOOR2(:val%2C%20:n)%20BEGIN%20FLOOR(:val%20*%2010.0%20%5E%20:n)%20/%2010.0%20%5E%20:n%20END%3B%20SELECT%20DISTINCT%20row.country%20AS%20country%2C%20%5Brow.sport...%5D%20AS%20sport%2C%20%5Brow.type...%5D%20AS%20type%20FROM%20%60/mongo/test/olympics%60%20AS%20row%20GROUP%20BY%20row.country%20ORDER%20BY%20row.country%20ASC"}}' --compressed
```

``` shell
curl 'http://localhost/mount/fs/mongo/test/Workspace.slam/.tmp/outf4d42a9f-bbef-4a31-81cc-61dca716a7b8/' -X PUT -H 'Content-Type: text/plain;charset=UTF-8' --data-binary '{"module":"CREATE FUNCTION cardf4d42a9fbbef4a3181cc61dca716a7b8(:filter) BEGIN SELECT DISTINCT * FROM `./../out76e34680-50ab-4547-bb10-44a913007dce` AS res WHERE :filter END"}' --compressed
```

And then this one is the failure:
``` shell
curl 'http://localhost/invoke/fs/mongo/test/Workspace.slam/.tmp/outf4d42a9f-bbef-4a31-81cc-61dca716a7b8/cardf4d42a9fbbef4a3181cc61dca716a7b8?filter=(country%20=%20%22AUS%22)&offset=0&limit=10' -H 'Accept: application/json;mode=readable' --compressed
```

I have a mongo mount named `mongo`, with a database in it called `test`, and in there I have the `olympics` test dataset from this repo.

**Comment by garyb** [comment] 2017-10-19 20:40
This also gives an interesting error, if run after the first two requests:
``` shell
curl 'http://localhost/query/fs/mongo/test/Workspace.slam/?q=IMPORT%20%60./.tmp/outf4d42a9f-bbef-4a31-81cc-61dca716a7b8/%60%3B%20tmp__0%20:=%20cardf4d42a9fbbef4a3181cc61dca716a7b8(:filter)%3B%20SELECT%20COUNT(*)%20AS%20count%20FROM%20(tmp__0)%20AS%20tmp__1&var.filter=true' -H 'Accept: application/json;mode=readable' --compressed
```

**Comment by jedesah** [comment] 2017-10-22 03:46
Okay, I figured out what's going on and why it was introduced in `25.0.16`.

The fix is very simple once one understands what's going on (the `Module` interpreter was using the vanilla `FileSystem` interpreter instead of the one that has views and modules overlaid on top). This was an oversight of mine in the recent refactoring I did in Quasar. I'm pretty sure referencing another module from within a function being invoked would fail as well.

Tomorrow I will add two tests asserting that both views and modules work properly when used in a module so that this doesn't happen again. Then I'll open a PR, so hopefully, the frontend team will have a fix for this sometime on Monday.

**Comment by cryogenian** [comment] 2017-10-25 19:14
The error still appears in 25.1.1

**Comment by cryogenian** [comment] 2017-10-25 19:26
Some details 

+ Create module 
`http://localhost:8080/mount/fs/test-mount/testDb/Join%20results.slam/.tmp/out3f38cf1b-3719-438e-bd56-da31c308ff67/`
```
{"module":"CREATE FUNCTION card3f38cf1b3719438ebd56da31c308ff67(:ordered_items, :customers, :items_inventory, :orders) BEGIN SELECT * FROM :customers END"}
```

+ Invoke module 
```
http://localhost:8080/invoke/fs/test-mount/testDb/Join%20results.slam/.tmp/out3f38cf1b-3719-438e-bd56-da31c308ff67/card3f38cf1b3719438ebd56da31c308ff67?ordered_items=%60/test-mount/testDb/ordered_items%60&customers=%60/test-mount/testDb/customers%60&items_inventory=%60/test-mount/testDb/items_inventory%60&orders=%60/test-mount/testDb/orders%60&offset=0&limit=300
```

In 25.0.16 other error is raised see slamdata/slamdata#2142

+ PUT view to 
`http://localhost:8080/mount/fs/test-mount/testDb/Join%20results.slam/.tmp/out39550606-7f76-4050-b619-b11ee248fe0d
`
```
{"view":{"connectionUri":"sql2:?q=SELECT%20o.order_key%20AS%20OrderKey%2C%20o.purchase_date%20AS%20PurchaseDate%2C%20c.last_name%20%7C%7C%20%22%2C%20%22%20%7C%7C%20c.first_name%20AS%20Name%2C%20c.city%20AS%20City%2C%20c.state%20AS%20State%2C%20i.clothing_size%20AS%20Size%2C%20i.clothing_type%20AS%20Type%2C%20i.clothing_color%20AS%20Color%2C%20i.price%20AS%20UnitPrice%2C%20oi.qty%20AS%20Quantity%2C%20i.price%20*%20oi.qty%20AS%20PricePaid%2C%20SUM(i.price%20*%20oi.qty)%20AS%20TotalPaid%2C%20i.clothing_brand%20AS%20Brand%20FROM%20(tmp__0)%20AS%20c%20INNER%20JOIN%20:orders%20AS%20o%20ON%20c.customer_key%20=%20o.customer_key%20INNER%20JOIN%20:ordered_items%20AS%20oi%20ON%20oi.order_key%20=%20o.order_key%20INNER%20JOIN%20:items_inventory%20AS%20i%20ON%20i.item_key%20=%20oi.item_key%20GROUP%20BY%20i.price%20*%20oi.qty&var.ordered_items=%60/test-mount/testDb/ordered_items%60&var.customers=%60/test-mount/testDb/customers%60&var.items_inventory=%60/test-mount/testDb/items_inventory%60&var.orders=%60/test-mount/testDb/orders%60&var.selection=(%22AK%22)"}}
```

+ Count above view 

```
ttp://localhost:8080/query/fs/test-mount/testDb/Join%20results.slam/?q=SELECT%20COUNT(*)%20AS%20count%20FROM%20%60./.tmp/out39550606-7f76-4050-b619-b11ee248fe0d%60&var.ordered_items=%60/test-mount/testDb/ordered_items%60&var.customers=%60/test-mount/testDb/customers%60&var.items_inventory=%60/test-mount/testDb/items_inventory%60&var.orders=%60/test-mount/testDb/orders%60&var.selection=(%22AK%22)
```

Output 400
```
{ "error": { "status": "No files to read from.", "detail": { "message": "No paths provided to read from.", "dirs": [] } } }
```

**Comment by jedesah** [comment] 2017-10-26 00:24
@cryogenian If I decode the query in the view this is what I get:

```
SELECT o.order_key AS OrderKey, o.purchase_date AS PurchaseDate, c.last_name || ", " || c.first_name AS Name, c.city AS City, c.state AS State, i.clothing_size AS Size, i.clothing_type AS Type, i.clothing_color AS Color, i.price AS UnitPrice, oi.qty AS Quantity, i.price * oi.qty AS PricePaid, SUM(i.price * oi.qty) AS TotalPaid, i.clothing_brand AS Brand FROM (tmp__0) AS c INNER JOIN :orders AS o ON c.customer_key = o.customer_key INNER JOIN :ordered_items AS oi ON oi.order_key = o.order_key INNER JOIN :items_inventory AS i ON i.item_key = oi.item_key GROUP BY i.price * oi.qty&var.ordered_items=`/test-mount/testDb/ordered_items`&var.customers=`/test-mount/testDb/customers`&var.items_inventory=`/test-mount/testDb/items_inventory`&var.orders=`/test-mount/testDb/orders`&var.selection=("AK")"}}
```

Where does `tmp__0` come from?

**Comment by cryogenian** [comment] 2017-10-26 17:06
Closing this, because this issue appears only when mimir and mongo both connected, and there is already pr for this problem.

**Comment by cryogenian** [comment] 2017-10-26 17:59
Well invoke endpoint is fixed and mongo/mimir stuff is known but I still get following error when try to count output collection
```json
{ "error": { "status": "No files to read from.", "detail": { "message": "No paths provided to read from.", "dirs": [] } } }
```
@slamdata/backend

**Comment by jedesah** [comment] 2017-11-23 00:02
We decided during the frontend meeting this morning that this was probably fixed. In any case, it was a bit of a catch-all so if something new (or old) shows up, we should open a new issue for it.

**Closed by jedesah** 2017-11-23 00:02 UTC
Labels: epic: WebApp: Quasar REST interfaces, status: In progress, type: Bug, ☠️
