### ISSUE TITLE
You have to kill REPL and Web process to get them to quit

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#3009] opened 2017-11-01 16:43 UTC
I noticed while running the web and REPL assemblies for Quasar 25.0.24 that you had to actually issue a `kill <process id>` to get the process to terminate when running from the command line. I just pulled down Quasar 26.0.0, and you still have to issue a `kill` command to to terminate the processes.

I don't know if it matters or not, but for the REPL I'm passing in `--backend:quasar.physical.mongodb.MongoDb\$=/Users/douglasduncan/quasar/plugins/26.0.0/quasar-mongodb-internal-assembly-26.0.0.jar` to load the MongoDB connector. For the web assembly I pass in `--plugins ~/quasar/plugins/26.0.0/`. The plugins folder has MongoDB, Couchbase and MarkLogic connector jar files in it.

In earlier versions of Quasar, you could press `CTRL-C` to terminate the Web assembly or type in `exit` to terminate the REPL.

**Comment by zeeiyerWork** [comment] 2017-11-02 16:58
REPL is not used by end-users. So hoping the fix can come later (for now i suppose a kill -9 might have to suffice).

**Comment by djspiewak** [comment] 2017-11-03 14:41
Duplicate of #2827.  I haven't seen this issue with REPL recently, but it doesn't surprise me.

**Closed** 2017-11-03 14:41 UTC
Labels: type: Bug
