### ISSUE TITLE
Simple count(*) performs very poorly

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1376] opened 2016-08-24 13:47 UTC
Two customers have stated that executing a `SELECT COUNT(*)` or similar causes Quasar to run an aggregate command rather than an equivalent .count() in MongoDB query language.  Testing confirms.

```
💪 $ select count(*) from patients
MongoDB
db.patients.aggregate(
  [
    {
      "$group": {
        "0": { "$sum": { "$literal": NumberInt("1") } },
        "_id": { "$literal": null }
      }
    },
    { "$limit": NumberLong("11") }],
  { "allowDiskUse": true });
```

One customer mentioned this took over 30 seconds in a large collection where the Mongo shell returned instantly.

Can this be optimized and prioritized?

**Comment by jdegoes** [comment] 2016-08-24 13:52
@mossprescott This is higher priority than #1371 and #1374 (if you're not already done with that).

**Comment by mossprescott** [comment] 2016-08-24 14:20
The problem seems to be isolated to the REPL. If I do the same query through the API, I can see it using the `count` command. The REPL is confusing the issue by adding a "limit" step which is unnecessary in a case like this, and defeats the optimization. Should be a quick fix.

**Comment by damonLL** [comment] 2016-08-24 14:24
Customer mentioned they traced the MongoDB command because of performance problems and noted it was from SlamData.  I will confirm this, however, and let you know.  Thank you!

**Comment by jdegoes** [comment] 2016-08-24 14:31
@damonLL The other thing to do is check to make sure it was just a simple `SELECT *`. If it had filters or other things on there, it likely wouldn't make it to `find().count()`.

**Comment by mossprescott** [comment] 2016-08-24 14:40
We execute with `count` even if there is filtering, as long as it can be compiled to the query language. Here's an example from the REPL with my fix:

```💪 $ select count(*) from zips where city = "BOULDER"
MongoDB
db.zips.count({ "city": "BOULDER" });


Query time: 0.0s
 0  |
----|
  7 |
```

PR coming up momentarily.

**Comment by jdegoes** [comment] 2016-08-24 14:41
@mossprescott Hmm, the front-end or the web API may auto-add a limit. Could that explain it?

**Comment by mossprescott** [comment] 2016-08-24 14:51
I didn't see it happen when I made direct calls to the API. The front-end will use paging, which turns in to a `limit` when a view read is interpreted, so that would explain it. I'll test that case as well.

**Comment by sellout** [comment] 2016-08-24 15:04
This unfortunately can’t solve the immediate problem, but I think this could be handled in QScript. We can elide a `Take` with a count that is statically >= 1 if the provenance is `Nil` (i.e., if there’s been a reduction applied such that we know we have exactly one record).

Does that sound like a reasonable solution for 3.1?

**Comment by mossprescott** [comment] 2016-08-24 15:08
I confirmed that the same problem occurs with views and is fixed in the PR.

All the `push -f` there is just me rewriting the commit message and changelog to capture everything ;)

**Comment by jdegoes** [comment] 2016-08-24 15:08
It [looks like count](https://api.mongodb.com/java/current/com/mongodb/client/MongoCollection.html#count-org.bson.conversions.Bson-com.mongodb.client.model.CountOptions-) can handle skip and limit.

**Comment by sellout** [comment] 2016-08-24 15:10
@jdegoes IIRC, those are applied _before_ the count reduction. I.e., it handles `Count(Limit(query, 10))`, not `Limit(Count(<query>), 10)`.

**Comment by damonLL** [comment] 2016-08-24 15:10
@mossprescott or @sellout:  would the same fix help a join query such as the following?

`SELECT count(*)  FROM coll1 INNER JOIN coll2 ON coll2._remote_id = coll1._client_id`

**Comment by sellout** [comment] 2016-08-24 15:16
@damonLL I haven't reviewed the fix yet, but it probably does. However, there is still join performance to deal with, so you probably want to be on Mongo 3.2 😉

**Comment by mossprescott** [comment] 2016-08-24 15:19
@sellout: as you'll see when you review the PR, the executor was handling `Count(Limit(...))` (which you can't generate with SQL^2), but not `Limit(Count(...))` (which you *can* write, but is also generated by either the REPL or reading from a view with, say, `?offset=0&limit=10`, as the front-end will do). It was easy to recognize a zero offset and limit >= 1 and ignore both, which is equivalent to what you suggest for QScript.

@damonLL: any JOIN is going to be map-reduce or at least aggregate, for some cases on 3.2.

**Comment by sellout** [comment] 2016-08-24 15:25
Are you sure you can’t write `Count(Limit(…))`? It seems easy enough to me, even just a sub-select, not even using any ² features.

does `Count(Join(…))` generate a single `aggregate` (or MR), or does it write a temp collection and `count` that? Something that may be worth doing cost analysis on.

**Comment by jdguzman** [comment] 2016-08-24 16:45
@sellout yes this is the right PR now.  But yeah this didn't have a huge effect for us.  We would be glad to share the query.

**Closed** 2016-08-24 16:46 UTC
Labels: bug
