### ISSUE TITLE
Lower and like in objects and oid

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#850] opened 2015-07-27 23:30 UTC
To #849 and slamdata/slamdata#352. Very similar with #715

searching anything containing `fin` without `"_id"` fields
```sql
SELECT * from "/demo/Untitled Notebook 2.slam/out2" where (
LOWER("value") LIKE '%fin%' OR 
LOWER("value"."year") LIKE '%fin%' OR 
LOWER("value"."city") LIKE '%fin%' OR 
LOWER("value"."sport") LIKE '%fin%' OR 
LOWER("value"."discipline") LIKE '%fin%' OR 
LOWER("value"."country") LIKE '%fin%' OR 
LOWER("value"."event") LIKE '%fin%' OR 
LOWER("value"."gender") LIKE '%fin%' OR 
LOWER("value"."type") LIKE '%fin%')
```

```
500 Internal Service Error
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed with error 16007: 'exception: can't convert from BSON type Object to String' on server localhost:27017. The full response is { "errmsg" : "exception: can't convert from BSON type Object to String", "code" : 16007, "ok" : 0.0 }
```

searching anything with `"_id"` fields
```sql
SELECT * from "/demo/Untitled Notebook 2.slam/out2" where (
LOWER("value"."_id") LIKE '%fin%' OR 
LOWER("value"."year") LIKE '%fin%' OR 
LOWER("value"."city") LIKE '%fin%' OR 
LOWER("value"."sport") LIKE '%fin%' OR 
LOWER("value"."discipline") LIKE '%fin%' OR 
LOWER("value"."country") LIKE '%fin%' OR 
LOWER("value"."event") LIKE '%fin%' OR 
LOWER("value"."gender") LIKE '%fin%' OR 
LOWER("value"."type") LIKE '%fin%')
```

```
500 Internal Service Error
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed with error 16007: 'exception: can't convert from BSON type OID to String' on server localhost:27017. The full response is { "errmsg" : "exception: can't convert from BSON type OID to String", "code" : 16007, "ok" : 0.0 }
```

What's the correct way to check if any field contains `fin`? 
Should we filter `"_id"` fields? 
Should we filter `"value"` fields in generated from search query sql? 
Should we filter `"value"` fields if there is only `"value"` field?

**Comment by sellout** [comment] 2015-07-27 23:49
This is partially a duplicate of #761. I already have a branch fixing the entire issue, and now that the ExprOp PR is decided, I should be able to get all of that in soon.

**Closed** 2015-12-11 16:43 UTC
Labels: bug, in progress
