### ISSUE TITLE
Bug: when I unmount the connector, close function is not called

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1781] opened 2016-12-14 11:53 UTC
When I unmount the connector `FileSystemDef.DefinitionResult` is not being called when using Slamdata (UI)

**Comment by wemrysi** [comment] 2016-12-14 14:31
@rabbitonweb Would you mind removing SlamData from the equation and testing using the HTTP API directly to delete a mount and see if the problem persists?

**Comment by alissapajer** [comment] 2017-06-21 15:15
@wemrysi I think this might have been fixed recently by something that @djspiewak uncovered? I can't find the PR though.

**Comment by wemrysi** [comment] 2017-06-21 15:29
There was #2289 which had to do with unmounting on shutdown of the repl/webserver, but I'm not sure if it applies here as this seems to deal with what actually happens when something is unmounted, not whether it was ever unmounted.

It doesn't seem like this was ever confirmed to be an issue with mounting or something else, maybe @rabbitonweb remembers?

**Comment by wemrysi** [comment] 2017-06-21 15:33
Actually, with that said, #2289 fixing the issue for `mimir` would imply that "close" action _is_ being called when a filesystem is umounted (as the problem was we weren't unmounting on shutdown).

**Comment by alissapajer** [comment] 2017-06-21 15:35
@wemrysi ah yeah that's true. I think we can close this issue then. @rabbitonweb if you are able to provide a way to reproduce this then please reopen it.

**Closed by alissapajer** 2017-06-21 15:35 UTC
Labels: epic: Connector: Generic Issues, type: Bug
