### ISSUE TITLE
The metadata endpoint for mimir mounts gives a 404 when the mount is empty

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2773] opened 2017-09-17 12:31 UTC
I'd expect a response like this instead:

``` json
{ "children": [] }
```

All the other mounts behave this way, and given the mount does actually exist it seems reasonable that it should return an empty list rather than "I don't exist".

**Comment by djspiewak** [comment] 2017-09-18 10:01
I've noticed this in the REPL too (there it shows up as an error).  My understanding was that this is actually a bug in the quasar filesystem, but if other mounts aren't exhibiting the same behavior, then that seems unlikely.  I'll investigate a bit more and see if I can figure out why it's happening.

**Comment by garyb** [comment] 2017-09-18 10:38
It's probably worth double checking that assertion... I think it's impossible to have an empty Mongo mount, so I might not have seen the exact scenario before.

**Comment by wemrysi** [comment] 2017-09-18 14:57
@djspiewak @garyb This looks like a duplicate of #2473, mind if we just reopen that one?

**Comment by garyb** [comment] 2017-09-18 15:15
Sure thing 👍

**Comment by djspiewak** [comment] 2017-09-22 18:55
Closing as duplicate of #2473.  I can confirm that this is indeed broken once again though.

**Closed by djspiewak** 2017-09-22 18:55 UTC
Labels: type: Bug
